<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_OeBBoIFIEe2uhP38WPXKYg" name="Acil Hizmetleri Süreci" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_OeBBoYFIEe2uhP38WPXKYg" name="Pool">
      <elements xmi:type="process:Lane" xmi:id="_OeBBooFIEe2uhP38WPXKYg" name="Employee lane" actor="_OeBBu4FIEe2uhP38WPXKYg">
        <elements xmi:type="process:StartEvent" xmi:id="_OeBBo4FIEe2uhP38WPXKYg" name="Başla" outgoing="_OeBBuIFIEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_OeBBpIFIEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_OeBBpYFIEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_OeBBpoFIEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_OeBBp4FIEe2uhP38WPXKYg" name="Hastanın müraacatı" outgoing="_jyZd4IFLEe2uhP38WPXKYg" incoming="_OeBBuIFIEe2uhP38WPXKYg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_OeBBqIFIEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_OeBBqYFIEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_OeBBqoFIEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_OeBBq4FIEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_OeBBrIFIEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_OeBBrYFIEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_OeBBroFIEe2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_OeBBr4FIEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_OeBBsIFIEe2uhP38WPXKYg">
            <targetForm xmi:type="expression:Expression" xmi:id="_OeBBsYFIEe2uhP38WPXKYg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_OeBBsoFIEe2uhP38WPXKYg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_OeBBs4FIEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_Ff1eUIFLEe2uhP38WPXKYg" name="Hastanın muayne edilmesi" outgoing="_kMex0IFLEe2uhP38WPXKYg" incoming="_jyZd4IFLEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Ff1eUoFLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Ff1eUYFLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Ff1eU4FLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Ff1eVIFLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Ff1eVYFLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Ff1eVoFLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Ff1eWIFLEe2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Ff1eV4FLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:InclusiveGateway" xmi:id="_IvfRMIFLEe2uhP38WPXKYg" name="Hastanın tedavisi hastanemizde yapılabilir mi ?" outgoing="_k5oywIFLEe2uhP38WPXKYg _l3e7EIFLEe2uhP38WPXKYg" incoming="_kMex0IFLEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_IvfRMoFLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_IvfRMYFLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_IvfRM4FLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_NMr1QIFLEe2uhP38WPXKYg" name="Hstanın sevk işlmelerinin yapılması" outgoing="_mq-NgIFLEe2uhP38WPXKYg" incoming="_l3e7EIFLEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_NMr1QoFLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_NMr1QYFLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_NMr1Q4FLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_NMr1RIFLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_NMr1RYFLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_NMr1RoFLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_NMr1SIFLEe2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_NMr1R4FLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:InclusiveGateway" xmi:id="_ZpLyMIFLEe2uhP38WPXKYg" name="Tetkik gerekli mi" outgoing="_vt4_gIFLEe2uhP38WPXKYg _y-nJYIFLEe2uhP38WPXKYg" incoming="_k5oywIFLEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ZpLyMoFLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ZpLyMYFLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ZpLyM4FLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ReceiveTask" xmi:id="_cgk2EIFLEe2uhP38WPXKYg" name="Hastaya ait epikriz notunun hazırlanması" outgoing="_nzJWgIFLEe2uhP38WPXKYg" incoming="_mq-NgIFLEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_cgk2EoFLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_cgk2EYFLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_cgk2E4FLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_cgk2FIFLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_cgk2FYFLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_cgk2FoFLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_cgk2GIFLEe2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_cgk2F4FLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_fxZGkIFLEe2uhP38WPXKYg" name="Hastanın ilgili kuruma sevki" outgoing="_okpr8IFLEe2uhP38WPXKYg" incoming="_nzJWgIFLEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_fxZGkoFLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_fxZGkYFLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_fxZGk4FLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_fxZGlIFLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_fxZGlYFLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_fxZGloFLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_fxZGmIFLEe2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_fxZGl4FLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_hiuhUIFLEe2uhP38WPXKYg" name="Son" incoming="_okpr8IFLEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_hiuhUoFLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_hiuhUYFLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_hiuhU4FLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_qcvO8IFLEe2uhP38WPXKYg" name="Tetkiklerin yapılması" outgoing="_017QUIFLEe2uhP38WPXKYg" incoming="_vt4_gIFLEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qcv2AYFLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qcv2AIFLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qcv2AoFLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_qcv2A4FLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_qcv2BIFLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_qcv2BYFLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_qcv2B4FLEe2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_qcv2BoFLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_swI08IFLEe2uhP38WPXKYg" name="Hastaya müdahale yönteminin belirlenmesi" outgoing="_EDyhoIFMEe2uhP38WPXKYg" incoming="_y-nJYIFLEe2uhP38WPXKYg _017QUIFLEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_swI08oFLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_swI08YFLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_swI084FLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_swI09IFLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_swI09YFLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_swI09oFLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_swI0-IFLEe2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_swI094FLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_67p4cIFLEe2uhP38WPXKYg" name="Müdahalenin yapılması" outgoing="_EexNcIFMEe2uhP38WPXKYg _x8E44IFMEe2uhP38WPXKYg" incoming="_EDyhoIFMEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_67p4coFLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_67p4cYFLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_67p4c4FLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_67p4dIFLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_67p4dYFLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_67p4doFLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_67p4eIFLEe2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_67p4d4FLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:InclusiveGateway" xmi:id="__8D3QIFLEe2uhP38WPXKYg" name="Müdahale sonucu" outgoing="_E1j80IFMEe2uhP38WPXKYg _lYnYUIFMEe2uhP38WPXKYg" incoming="_EexNcIFMEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="__8D3QoFLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="__8D3QYFLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="__8D3Q4FLEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:InclusiveGateway" xmi:id="_Bs3GgIFMEe2uhP38WPXKYg" name="Müdahale sonucu" outgoing="_I6z68IFMEe2uhP38WPXKYg _RRkKgIFMEe2uhP38WPXKYg _nJ5IsIFMEe2uhP38WPXKYg" incoming="_E1j80IFMEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Bs3GgoFMEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Bs3GgYFMEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Bs3Gg4FMEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_F_-hgIFMEe2uhP38WPXKYg" name="Ameliyatın yapılması" outgoing="_KRbIkIFMEe2uhP38WPXKYg" incoming="_I6z68IFMEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_F__IkYFMEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_F__IkIFMEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_F__IkoFMEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_F__Ik4FMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_F__IlIFMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_F__IlYFMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_F__Il4FMEe2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_F__IloFMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_H3omsIFMEe2uhP38WPXKYg" name="Son" incoming="_KRbIkIFMEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_H3omsoFMEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_H3omsYFMEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_H3oms4FMEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_OayxsIFMEe2uhP38WPXKYg" name="Defin işlemlerinin başlatılması" outgoing="_SC9LMIFMEe2uhP38WPXKYg" incoming="_RRkKgIFMEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_OayxsoFMEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_OayxsYFMEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Oayxs4FMEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_OayxtIFMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_OayxtYFMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_OayxtoFMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_OayxuIFMEe2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Oayxt4FMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_QQu_oIFMEe2uhP38WPXKYg" name="Son" incoming="_SC9LMIFMEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QQu_ooFMEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QQu_oYFMEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QQu_o4FMEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_WFaUAIFMEe2uhP38WPXKYg" name="Hastanın müşahade odasına alınması" outgoing="_saVHkIFMEe2uhP38WPXKYg" incoming="_lYnYUIFMEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_WFaUAoFMEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_WFaUAYFMEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_WFaUA4FMEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_WFaUBIFMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_WFaUBYFMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_WFaUBoFMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_WFaUCIFMEe2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_WFaUB4FMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_ZNW8YIFMEe2uhP38WPXKYg" name="Müşahade sonucu" outgoing="_oFToEIFMEe2uhP38WPXKYg _vk60QIFMEe2uhP38WPXKYg" incoming="_saVHkIFMEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ZNW8YoFMEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ZNW8YYFMEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ZNW8Y4FMEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ZNW8ZIFMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ZNW8ZYFMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ZNW8ZoFMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ZNW8aIFMEe2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ZNW8Z4FMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ReceiveTask" xmi:id="_dvJskIFMEe2uhP38WPXKYg" name="Yatış işlemlerinin yapılması ve vezneye kayıt" outgoing="_IeybYIFOEe2uhP38WPXKYg" incoming="_nJ5IsIFMEe2uhP38WPXKYg _oFToEIFMEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dvJskoFMEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dvJskYFMEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dvJsk4FMEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_dvJslIFMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_dvJslYFMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_dvJsloFMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_dvJsmIFMEe2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_dvJsl4FMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ReceiveTask" xmi:id="_h7ApAIFMEe2uhP38WPXKYg" name="İşlemlerin ve hasta bilgilerinin kaydedilmesi" outgoing="_JHTM4IFOEe2uhP38WPXKYg" incoming="_vk60QIFMEe2uhP38WPXKYg _x8E44IFMEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_h7BQEYFMEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_h7BQEIFMEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_h7BQEoFMEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_h7BQE4FMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_h7BQFIFMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_h7BQFYFMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_h7BQF4FMEe2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_h7BQFoFMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ReceiveTask" xmi:id="_46HzoIFNEe2uhP38WPXKYg" name="İşlemlerin ve hasta bilgilerinin kaydedilmesi" outgoing="_o8bycIFOEe2uhP38WPXKYg" incoming="_IeybYIFOEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_46OhUIFNEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_46N6QIFNEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_46OhUYFNEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_46OhUoFNEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_46OhU4FNEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_46OhVIFNEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_46OhVoFNEe2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_46OhVYFNEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ReceiveTask" xmi:id="_ALH8EIFOEe2uhP38WPXKYg" name="Faturalama işlemlerinin tamamlanması" outgoing="_jLNasIFOEe2uhP38WPXKYg" incoming="_J7GoYIFOEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ALH8EoFOEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ALH8EYFOEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ALH8E4FOEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ALH8FIFOEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ALH8FYFOEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ALH8FoFOEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ALH8GIFOEe2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ALH8F4FOEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:InclusiveGateway" xmi:id="_EKZOAIFOEe2uhP38WPXKYg" name="Hastanın sosyal güvencesi var mı" outgoing="_J7GoYIFOEe2uhP38WPXKYg _PRk90IFOEe2uhP38WPXKYg" incoming="_JHTM4IFOEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_EKZOAoFOEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_EKZOAYFOEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_EKZOA4FOEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ReceiveTask" xmi:id="_L_2uYIFOEe2uhP38WPXKYg" name="Faturalama işlemlerinin tamamlanması" outgoing="_yiyosIFOEe2uhP38WPXKYg" incoming="_PRk90IFOEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_L_3VcYFOEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_L_3VcIFOEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_L_3VcoFOEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_L_3Vc4FOEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_L_3VdIFOEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_L_3VdYFOEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_L_3Vd4FOEe2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_L_3VdoFOEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_dZxnkIFOEe2uhP38WPXKYg" name="Tedavi ücretlerinin ilgili sosyal güvenceye göre hazırlanması" outgoing="_zEVPgIFOEe2uhP38WPXKYg" incoming="_jLNasIFOEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dZxnkoFOEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dZxnkYFOEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dZxnk4FOEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_dZxnlIFOEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_dZxnlYFOEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_dZxnloFOEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_dZxnmIFOEe2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_dZxnl4FOEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_lEc0QIFOEe2uhP38WPXKYg" name="Servis yatış işlemlerinin yapılması" outgoing="_zZfnMIFOEe2uhP38WPXKYg" incoming="_o8bycIFOEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_lEc0QoFOEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_lEc0QYFOEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_lEc0Q4FOEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_lEc0RIFOEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_lEc0RYFOEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_lEc0RoFOEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_lEc0SIFOEe2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_lEc0R4FOEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_r0e9oIFOEe2uhP38WPXKYg" name="Tedavi ücretlerinin tahsilatı" outgoing="_yy124IFOEe2uhP38WPXKYg" incoming="_yiyosIFOEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_r0e9ooFOEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_r0e9oYFOEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_r0e9o4FOEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_r0e9pIFOEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_r0e9pYFOEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_r0e9poFOEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_r0e9qIFOEe2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_r0e9p4FOEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_u_9bIIFOEe2uhP38WPXKYg" name="Son" incoming="_yy124IFOEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_u_-CMYFOEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_u_-CMIFOEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_u_-CMoFOEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_vWmZgIFOEe2uhP38WPXKYg" name="Son" incoming="_zEVPgIFOEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_vWmZgoFOEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_vWmZgYFOEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_vWmZg4FOEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_vm0m0IFOEe2uhP38WPXKYg" name="Son" incoming="_zZfnMIFOEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_vm1N4YFOEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_vm1N4IFOEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_vm1N4oFOEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_OeBBtIFIEe2uhP38WPXKYg">
        <targetForm xmi:type="expression:Expression" xmi:id="_OeBBtYFIEe2uhP38WPXKYg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_OeBBtoFIEe2uhP38WPXKYg">
        <targetForm xmi:type="expression:Expression" xmi:id="_OeBBt4FIEe2uhP38WPXKYg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_OeBBuIFIEe2uhP38WPXKYg" target="_OeBBp4FIEe2uhP38WPXKYg" source="_OeBBo4FIEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_OeBBuYFIEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_OeBBuoFIEe2uhP38WPXKYg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jyZd4IFLEe2uhP38WPXKYg" target="_Ff1eUIFLEe2uhP38WPXKYg" source="_OeBBp4FIEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jyZd4YFLEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_jyZd4oFLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kMex0IFLEe2uhP38WPXKYg" target="_IvfRMIFLEe2uhP38WPXKYg" source="_Ff1eUIFLEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kMex0YFLEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_kMex0oFLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_k5oywIFLEe2uhP38WPXKYg" name="Evet" target="_ZpLyMIFLEe2uhP38WPXKYg" source="_IvfRMIFLEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_k5oywYFLEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_k5oywoFLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_l3e7EIFLEe2uhP38WPXKYg" name="Hayır" target="_NMr1QIFLEe2uhP38WPXKYg" source="_IvfRMIFLEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_l3e7EYFLEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_l3e7EoFLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_mq-NgIFLEe2uhP38WPXKYg" target="_cgk2EIFLEe2uhP38WPXKYg" source="_NMr1QIFLEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_mq-NgYFLEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_mq-NgoFLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_nzJWgIFLEe2uhP38WPXKYg" target="_fxZGkIFLEe2uhP38WPXKYg" source="_cgk2EIFLEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_nzJWgYFLEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_nzJWgoFLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_okpr8IFLEe2uhP38WPXKYg" target="_hiuhUIFLEe2uhP38WPXKYg" source="_fxZGkIFLEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_okpr8YFLEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_okpr8oFLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_vt4_gIFLEe2uhP38WPXKYg" name="Evet" target="_qcvO8IFLEe2uhP38WPXKYg" source="_ZpLyMIFLEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_vt4_gYFLEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_vt4_goFLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_y-nJYIFLEe2uhP38WPXKYg" name="Hayır" target="_swI08IFLEe2uhP38WPXKYg" source="_ZpLyMIFLEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_y-nJYYFLEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_y-nJYoFLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_017QUIFLEe2uhP38WPXKYg" target="_swI08IFLEe2uhP38WPXKYg" source="_qcvO8IFLEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_017QUYFLEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_017QUoFLEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_EDyhoIFMEe2uhP38WPXKYg" target="_67p4cIFLEe2uhP38WPXKYg" source="_swI08IFLEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_EDzIsIFMEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_EDzIsYFMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_EexNcIFMEe2uhP38WPXKYg" target="__8D3QIFLEe2uhP38WPXKYg" source="_67p4cIFLEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_EexNcYFMEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_EexNcoFMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_E1j80IFMEe2uhP38WPXKYg" target="_Bs3GgIFMEe2uhP38WPXKYg" source="__8D3QIFLEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_E1j80YFMEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_E1j80oFMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_I6z68IFMEe2uhP38WPXKYg" name="Ameliyat" target="_F_-hgIFMEe2uhP38WPXKYg" source="_Bs3GgIFMEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_I6z68YFMEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_I6z68oFMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_KRbIkIFMEe2uhP38WPXKYg" target="_H3omsIFMEe2uhP38WPXKYg" source="_F_-hgIFMEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_KRbIkYFMEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_KRbIkoFMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RRkKgIFMEe2uhP38WPXKYg" name="Ölüm" target="_OayxsIFMEe2uhP38WPXKYg" source="_Bs3GgIFMEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RRkKgYFMEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_RRkKgoFMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SC9LMIFMEe2uhP38WPXKYg" target="_QQu_oIFMEe2uhP38WPXKYg" source="_OayxsIFMEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SC9LMYFMEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_SC9LMoFMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_lYnYUIFMEe2uhP38WPXKYg" name="Müşahade" target="_WFaUAIFMEe2uhP38WPXKYg" source="__8D3QIFLEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_lYnYUYFMEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_lYnYUoFMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_nJ5IsIFMEe2uhP38WPXKYg" name="Yatış yapılacak" target="_dvJskIFMEe2uhP38WPXKYg" source="_Bs3GgIFMEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_nJ5IsYFMEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_nJ5IsoFMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_oFToEIFMEe2uhP38WPXKYg" name="Yatış yapılacak" target="_dvJskIFMEe2uhP38WPXKYg" source="_ZNW8YIFMEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_oFToEYFMEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_oFToEoFMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_saVHkIFMEe2uhP38WPXKYg" target="_ZNW8YIFMEe2uhP38WPXKYg" source="_WFaUAIFMEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_saVHkYFMEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_saVHkoFMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_vk60QIFMEe2uhP38WPXKYg" name="Taburcu olacak" target="_h7ApAIFMEe2uhP38WPXKYg" source="_ZNW8YIFMEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_vk60QYFMEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_vk60QoFMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_x8E44IFMEe2uhP38WPXKYg" name="Taburcu" target="_h7ApAIFMEe2uhP38WPXKYg" source="_67p4cIFLEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_x8E44YFMEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_x8E44oFMEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IeybYIFOEe2uhP38WPXKYg" target="_46HzoIFNEe2uhP38WPXKYg" source="_dvJskIFMEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IeybYYFOEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_IeybYoFOEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_JHTM4IFOEe2uhP38WPXKYg" target="_EKZOAIFOEe2uhP38WPXKYg" source="_h7ApAIFMEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_JHTz8IFOEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_JHTz8YFOEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_J7GoYIFOEe2uhP38WPXKYg" name="Evet" target="_ALH8EIFOEe2uhP38WPXKYg" source="_EKZOAIFOEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_J7GoYYFOEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_J7GoYoFOEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PRk90IFOEe2uhP38WPXKYg" name="Hayır" target="_L_2uYIFOEe2uhP38WPXKYg" source="_EKZOAIFOEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PRk90YFOEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_PRk90oFOEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jLNasIFOEe2uhP38WPXKYg" target="_dZxnkIFOEe2uhP38WPXKYg" source="_ALH8EIFOEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jLNasYFOEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_jLNasoFOEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_o8bycIFOEe2uhP38WPXKYg" target="_lEc0QIFOEe2uhP38WPXKYg" source="_46HzoIFNEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_o8bycYFOEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_o8bycoFOEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_yiyosIFOEe2uhP38WPXKYg" target="_r0e9oIFOEe2uhP38WPXKYg" source="_L_2uYIFOEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_yiyosYFOEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_yiyosoFOEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_yy124IFOEe2uhP38WPXKYg" target="_u_9bIIFOEe2uhP38WPXKYg" source="_r0e9oIFOEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_yy2d8IFOEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_yy2d8YFOEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_zEVPgIFOEe2uhP38WPXKYg" target="_vWmZgIFOEe2uhP38WPXKYg" source="_dZxnkIFOEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_zEV2kIFOEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_zEV2kYFOEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_zZfnMIFOEe2uhP38WPXKYg" target="_vm0m0IFOEe2uhP38WPXKYg" source="_lEc0QIFOEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_zZfnMYFOEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_zZfnMoFOEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_OeBBu4FIEe2uhP38WPXKYg" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_OeBBvIFIEe2uhP38WPXKYg"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_OeBBvYFIEe2uhP38WPXKYg">
        <name xmi:type="expression:Expression" xmi:id="_OeBBvoFIEe2uhP38WPXKYg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_OeBBv4FIEe2uhP38WPXKYg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_OeBBwIFIEe2uhP38WPXKYg">
        <name xmi:type="expression:Expression" xmi:id="_OeBBwYFIEe2uhP38WPXKYg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_OeBBwoFIEe2uhP38WPXKYg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_OeBBw4FIEe2uhP38WPXKYg">
        <name xmi:type="expression:Expression" xmi:id="_OeBBxIFIEe2uhP38WPXKYg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_OeBBxYFIEe2uhP38WPXKYg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_OeBBxoFIEe2uhP38WPXKYg">
        <name xmi:type="expression:Expression" xmi:id="_OeBBx4FIEe2uhP38WPXKYg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_OeBByIFIEe2uhP38WPXKYg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_OeBByYFIEe2uhP38WPXKYg">
        <name xmi:type="expression:Expression" xmi:id="_OeBByoFIEe2uhP38WPXKYg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_OeBBy4FIEe2uhP38WPXKYg" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_OeBBzIFIEe2uhP38WPXKYg" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_OeBBzYFIEe2uhP38WPXKYg" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_OeBBzoFIEe2uhP38WPXKYg" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_OeBBz4FIEe2uhP38WPXKYg" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_OeBB0IFIEe2uhP38WPXKYg" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_OeBB0YFIEe2uhP38WPXKYg" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_OeBB0oFIEe2uhP38WPXKYg" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_OeBB04FIEe2uhP38WPXKYg" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_OeBB1IFIEe2uhP38WPXKYg" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_OeBB1YFIEe2uhP38WPXKYg" type="Process" element="_OeBBoIFIEe2uhP38WPXKYg" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_OeBB1oFIEe2uhP38WPXKYg" type="2007" element="_OeBBoYFIEe2uhP38WPXKYg">
      <children xmi:type="notation:DecorationNode" xmi:id="_OeBB14FIEe2uhP38WPXKYg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_OeBB2IFIEe2uhP38WPXKYg" type="7001">
        <children xmi:type="notation:Node" xmi:id="_OeBB2YFIEe2uhP38WPXKYg" type="3007" element="_OeBBooFIEe2uhP38WPXKYg">
          <children xmi:type="notation:DecorationNode" xmi:id="_OeBB2oFIEe2uhP38WPXKYg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_OeBB24FIEe2uhP38WPXKYg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_OeBB3IFIEe2uhP38WPXKYg" type="3005" element="_OeBBp4FIEe2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_OeBB3YFIEe2uhP38WPXKYg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OeBB3oFIEe2uhP38WPXKYg" x="160" y="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_OeBB34FIEe2uhP38WPXKYg" type="3002" element="_OeBBo4FIEe2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_OeBB4IFIEe2uhP38WPXKYg" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_OeBB4YFIEe2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OeBB4oFIEe2uhP38WPXKYg" x="60" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ff2FYIFLEe2uhP38WPXKYg" type="3006" element="_Ff1eUIFLEe2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ff2FYoFLEe2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ff2FYYFLEe2uhP38WPXKYg" x="350" y="60" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ivf4QIFLEe2uhP38WPXKYg" type="3051" element="_IvfRMIFLEe2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ivf4QoFLEe2uhP38WPXKYg" type="5075">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Ivf4Q4FLEe2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ivf4QYFLEe2uhP38WPXKYg" x="624" y="82"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_NMr1SYFLEe2uhP38WPXKYg" type="3006" element="_NMr1QIFLEe2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_NMr1S4FLEe2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NMr1SoFLEe2uhP38WPXKYg" x="830" y="55" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZpMZQIFLEe2uhP38WPXKYg" type="3051" element="_ZpLyMIFLEe2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZpMZQoFLEe2uhP38WPXKYg" type="5075">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ZpMZQ4FLEe2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZpMZQYFLEe2uhP38WPXKYg" x="622" y="232"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_cgk2GYFLEe2uhP38WPXKYg" type="3026" element="_cgk2EIFLEe2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_cgldIIFLEe2uhP38WPXKYg" type="5012"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_cgk2GoFLEe2uhP38WPXKYg" x="1098" y="62" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_fxZGmYFLEe2uhP38WPXKYg" type="3006" element="_fxZGkIFLEe2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_fxZGm4FLEe2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fxZGmoFLEe2uhP38WPXKYg" x="1157" y="206" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_hiuhVIFLEe2uhP38WPXKYg" type="3003" element="_hiuhUIFLEe2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_hivIYIFLEe2uhP38WPXKYg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_hivIYYFLEe2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_hiuhVYFLEe2uhP38WPXKYg" x="1203" y="330"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_qcv2CIFLEe2uhP38WPXKYg" type="3006" element="_qcvO8IFLEe2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_qcv2CoFLEe2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qcv2CYFLEe2uhP38WPXKYg" x="183" y="251" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_swI0-YFLEe2uhP38WPXKYg" type="3006" element="_swI08IFLEe2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_swJcAIFLEe2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_swI0-oFLEe2uhP38WPXKYg" x="173" y="402" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_67qfgIFLEe2uhP38WPXKYg" type="3006" element="_67p4cIFLEe2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_67qfgoFLEe2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_67qfgYFLEe2uhP38WPXKYg" x="173" y="570" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="__8D3RIFLEe2uhP38WPXKYg" type="3051" element="__8D3QIFLEe2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="__8D3RoFLEe2uhP38WPXKYg" type="5075">
                <layoutConstraint xmi:type="notation:Location" xmi:id="__8D3R4FLEe2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__8D3RYFLEe2uhP38WPXKYg" x="527" y="527"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Bs3GhIFMEe2uhP38WPXKYg" type="3051" element="_Bs3GgIFMEe2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Bs3tkIFMEe2uhP38WPXKYg" type="5075">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Bs3tkYFMEe2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Bs3GhYFMEe2uhP38WPXKYg" x="883" y="582"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_F__voIFMEe2uhP38WPXKYg" type="3006" element="_F_-hgIFMEe2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_F__vooFMEe2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_F__voYFMEe2uhP38WPXKYg" x="845" y="407" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_H3omtIFMEe2uhP38WPXKYg" type="3003" element="_H3omsIFMEe2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_H3omtoFMEe2uhP38WPXKYg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_H3omt4FMEe2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_H3omtYFMEe2uhP38WPXKYg" x="882" y="266"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_OayxuYFMEe2uhP38WPXKYg" type="3006" element="_OayxsIFMEe2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Oayxu4FMEe2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OayxuoFMEe2uhP38WPXKYg" x="1110" y="592" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_QQu_pIFMEe2uhP38WPXKYg" type="3003" element="_QQu_oIFMEe2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_QQu_poFMEe2uhP38WPXKYg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_QQu_p4FMEe2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_QQu_pYFMEe2uhP38WPXKYg" x="1155" y="724"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_WFa7EIFMEe2uhP38WPXKYg" type="3006" element="_WFaUAIFMEe2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_WFa7EoFMEe2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_WFa7EYFMEe2uhP38WPXKYg" x="481" y="709" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZNXjcIFMEe2uhP38WPXKYg" type="3006" element="_ZNW8YIFMEe2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZNXjcoFMEe2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZNXjcYFMEe2uhP38WPXKYg" x="494" y="890"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_dvJsmYFMEe2uhP38WPXKYg" type="3026" element="_dvJskIFMEe2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_dvJsm4FMEe2uhP38WPXKYg" type="5012"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dvJsmoFMEe2uhP38WPXKYg" x="845" y="906" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_h7BQGIFMEe2uhP38WPXKYg" type="3026" element="_h7ApAIFMEe2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_h7BQGoFMEe2uhP38WPXKYg" type="5012"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_h7BQGYFMEe2uhP38WPXKYg" x="153" y="890" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_46OhV4FNEe2uhP38WPXKYg" type="3026" element="_46HzoIFNEe2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_46OhWYFNEe2uhP38WPXKYg" type="5012"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_46OhWIFNEe2uhP38WPXKYg" x="854" y="1122" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ALH8GYFOEe2uhP38WPXKYg" type="3026" element="_ALH8EIFOEe2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ALH8G4FOEe2uhP38WPXKYg" type="5012"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ALH8GoFOEe2uhP38WPXKYg" x="374" y="1114" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_EKZOBIFOEe2uhP38WPXKYg" type="3051" element="_EKZOAIFOEe2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_EKZ1EIFOEe2uhP38WPXKYg" type="5075">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_EKZ1EYFOEe2uhP38WPXKYg" x="-27" y="9"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EKZOBYFOEe2uhP38WPXKYg" x="191" y="1122"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_L_3VeIFOEe2uhP38WPXKYg" type="3026" element="_L_2uYIFOEe2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_L_3VeoFOEe2uhP38WPXKYg" type="5012"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_L_3VeYFOEe2uhP38WPXKYg" x="134" y="1314" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_dZyOoIFOEe2uhP38WPXKYg" type="3006" element="_dZxnkIFOEe2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_dZyOooFOEe2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dZyOoYFOEe2uhP38WPXKYg" x="374" y="1304" width="160" height="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_lEc0SYFOEe2uhP38WPXKYg" type="3006" element="_lEc0QIFOEe2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_lEc0S4FOEe2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_lEc0SoFOEe2uhP38WPXKYg" x="864" y="1304" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_r0fksIFOEe2uhP38WPXKYg" type="3006" element="_r0e9oIFOEe2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_r0fksoFOEe2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_r0fksYFOEe2uhP38WPXKYg" x="134" y="1474" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_u_-CM4FOEe2uhP38WPXKYg" type="3003" element="_u_9bIIFOEe2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_u_-CNYFOEe2uhP38WPXKYg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_u_-CNoFOEe2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_u_-CNIFOEe2uhP38WPXKYg" x="278" y="1554"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_vWnAkIFOEe2uhP38WPXKYg" type="3003" element="_vWmZgIFOEe2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_vWnAkoFOEe2uhP38WPXKYg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_vWnAk4FOEe2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vWnAkYFOEe2uhP38WPXKYg" x="452" y="1468"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_vm1N44FOEe2uhP38WPXKYg" type="3003" element="_vm0m0IFOEe2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_vm1N5YFOEe2uhP38WPXKYg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_vm1N5oFOEe2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vm1N5IFOEe2uhP38WPXKYg" x="934" y="1465"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_OeBB44FIEe2uhP38WPXKYg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_OeBB5IFIEe2uhP38WPXKYg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_OeBB5YFIEe2uhP38WPXKYg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_OeBB5oFIEe2uhP38WPXKYg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OeBB54FIEe2uhP38WPXKYg" x="53" y="10" width="1348" height="1900"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_OeBB6IFIEe2uhP38WPXKYg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_OeBB6YFIEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_OeBB6oFIEe2uhP38WPXKYg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_OeBB64FIEe2uhP38WPXKYg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OeBB7IFIEe2uhP38WPXKYg" width="1376" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_OeBB7YFIEe2uhP38WPXKYg"/>
    <edges xmi:type="notation:Connector" xmi:id="_OeBB7oFIEe2uhP38WPXKYg" type="4001" element="_OeBBuIFIEe2uhP38WPXKYg" source="_OeBB34FIEe2uhP38WPXKYg" target="_OeBB3IFIEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_OeBB74FIEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_OeBosIFIEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_OeBosYFIEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_OeBosoFIEe2uhP38WPXKYg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jyaE8IFLEe2uhP38WPXKYg" type="4001" element="_jyZd4IFLEe2uhP38WPXKYg" source="_OeBB3IFIEe2uhP38WPXKYg" target="_Ff2FYIFLEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jyaE84FLEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jyaE9IFLEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jyaE8YFLEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jyaE8oFLEe2uhP38WPXKYg" points="[0, 0, -150, -2]$[156, 32, 6, 30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_jyasAIFLEe2uhP38WPXKYg" id="(1.0,0.56)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kMex04FLEe2uhP38WPXKYg" type="4001" element="_kMex0IFLEe2uhP38WPXKYg" source="_Ff2FYIFLEe2uhP38WPXKYg" target="_Ivf4QIFLEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_kMfY4IFLEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kMfY4YFLEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kMex1IFLEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kMex1YFLEe2uhP38WPXKYg" points="[0, 4, -187, 0]$[189, 2, 2, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_kMf_8IFLEe2uhP38WPXKYg" id="(1.0,0.55)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_kMf_8YFLEe2uhP38WPXKYg" id="(0.7674418604651163,0.3488372093023256)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_k5pZ0IFLEe2uhP38WPXKYg" type="4001" element="_k5oywIFLEe2uhP38WPXKYg" source="_Ivf4QIFLEe2uhP38WPXKYg" target="_ZpMZQIFLEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_k5pZ04FLEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_k5pZ1IFLEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_k5pZ0YFLEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_k5pZ0oFLEe2uhP38WPXKYg" points="[-23, 18, 4, -140]$[-29, 163, -2, 5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_k5qA4IFLEe2uhP38WPXKYg" id="(1.0,0.5813953488372093)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_k5qA4YFLEe2uhP38WPXKYg" id="(0.4186046511627907,0.7674418604651163)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_l3e7E4FLEe2uhP38WPXKYg" type="4001" element="_l3e7EIFLEe2uhP38WPXKYg" source="_Ivf4QIFLEe2uhP38WPXKYg" target="_NMr1SYFLEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_l3fiIIFLEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_l3fiIYFLEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_l3e7FIFLEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_l3e7FYFLEe2uhP38WPXKYg" points="[-5, 0, -228, 22]$[283, -17, 60, 5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_l3fiIoFLEe2uhP38WPXKYg" id="(1.0,0.5813953488372093)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_mq-Ng4FLEe2uhP38WPXKYg" type="4001" element="_mq-NgIFLEe2uhP38WPXKYg" source="_NMr1SYFLEe2uhP38WPXKYg" target="_cgk2GYFLEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_mq-NhoFLEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_mq-Nh4FLEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_mq-NhIFLEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_mq-NhYFLEe2uhP38WPXKYg" points="[0, 0, -218, -13]$[148, 15, -70, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_mq-0kIFLEe2uhP38WPXKYg" id="(1.0,0.48333333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_nzJWg4FLEe2uhP38WPXKYg" type="4001" element="_nzJWgIFLEe2uhP38WPXKYg" source="_cgk2GYFLEe2uhP38WPXKYg" target="_fxZGmYFLEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_nzJ9kIFLEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_nzJ9kYFLEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_nzJWhIFLEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_nzJWhYFLEe2uhP38WPXKYg" points="[-5, 39, 8, -84]$[-9, 113, 4, -10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_nzKkoIFLEe2uhP38WPXKYg" id="(1.0,0.44285714285714284)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_nzKkoYFLEe2uhP38WPXKYg" id="(0.5666666666666667,0.16666666666666666)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_okpr84FLEe2uhP38WPXKYg" type="4001" element="_okpr8IFLEe2uhP38WPXKYg" source="_fxZGmYFLEe2uhP38WPXKYg" target="_hiuhVIFLEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_okpr9oFLEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_okpr94FLEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_okpr9IFLEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_okpr9YFLEe2uhP38WPXKYg" points="[-20, 34, 39, -71]$[-59, 98, 0, -7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_okqTAIFLEe2uhP38WPXKYg" id="(1.0,0.43333333333333335)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_okqTAYFLEe2uhP38WPXKYg" id="(0.5,0.23333333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_vt5mkIFLEe2uhP38WPXKYg" type="4001" element="_vt4_gIFLEe2uhP38WPXKYg" source="_ZpMZQIFLEe2uhP38WPXKYg" target="_qcv2CIFLEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_vt5mk4FLEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_vt5mlIFLEe2uhP38WPXKYg" x="26" y="-7"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_vt5mkYFLEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_vt5mkoFLEe2uhP38WPXKYg" points="[-30, 2, 184, -15]$[-154, 18, 60, 1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_vt6NoIFLEe2uhP38WPXKYg" id="(1.0,0.7441860465116279)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_y-nwcIFLEe2uhP38WPXKYg" type="4001" element="_y-nJYIFLEe2uhP38WPXKYg" source="_ZpMZQIFLEe2uhP38WPXKYg" target="_swI0-YFLEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_y-nwc4FLEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_y-nwdIFLEe2uhP38WPXKYg" x="65" y="-12"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_y-nwcYFLEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_y-nwcoFLEe2uhP38WPXKYg" points="[-27, 13, 222, -115]$[-233, 126, 16, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_y-oXgIFLEe2uhP38WPXKYg" id="(1.0,0.5581395348837209)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_y-oXgYFLEe2uhP38WPXKYg" id="(0.8857142857142857,0.42857142857142855)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_017QU4FLEe2uhP38WPXKYg" type="4001" element="_017QUIFLEe2uhP38WPXKYg" source="_qcv2CIFLEe2uhP38WPXKYg" target="_swI0-YFLEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_017QVoFLEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_017QV4FLEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_017QVIFLEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_017QVYFLEe2uhP38WPXKYg" points="[-20, 34, 40, -78]$[-63, 77, -3, -35]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_0173YIFLEe2uhP38WPXKYg" id="(1.0,0.43333333333333335)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_EDzIsoFMEe2uhP38WPXKYg" type="4001" element="_EDyhoIFMEe2uhP38WPXKYg" source="_swI0-YFLEe2uhP38WPXKYg" target="_67qfgIFLEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_EDzItYFMEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_EDzItoFMEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_EDzIs4FMEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_EDzItIFMEe2uhP38WPXKYg" points="[-18, 43, 62, -128]$[-20, 168, 60, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_EDzvwIFMEe2uhP38WPXKYg" id="(1.0,0.38571428571428573)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_EexNc4FMEe2uhP38WPXKYg" type="4001" element="_EexNcIFMEe2uhP38WPXKYg" source="_67qfgIFLEe2uhP38WPXKYg" target="__8D3RIFLEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Eex0gYFMEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Eex0goFMEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_EexNdIFMEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Eex0gIFMEe2uhP38WPXKYg" points="[0, -2, -264, 0]$[269, -2, 5, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Eex0g4FMEe2uhP38WPXKYg" id="(1.0,0.4)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Eex0hIFMEe2uhP38WPXKYg" id="(0.8372093023255814,0.5116279069767442)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_E1j804FMEe2uhP38WPXKYg" type="4001" element="_E1j80IFMEe2uhP38WPXKYg" source="__8D3RIFLEe2uhP38WPXKYg" target="_Bs3GhIFMEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_E1j81oFMEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_E1j814FMEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_E1j81IFMEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_E1j81YFMEe2uhP38WPXKYg" points="[-9, 4, -337, 0]$[323, 2, -5, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_E1kj4IFMEe2uhP38WPXKYg" id="(1.0,0.6046511627906976)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_E1kj4YFMEe2uhP38WPXKYg" id="(0.20930232558139536,0.4186046511627907)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_I6z684FMEe2uhP38WPXKYg" type="4001" element="_I6z68IFMEe2uhP38WPXKYg" source="_Bs3GhIFMEe2uhP38WPXKYg" target="_F__voIFMEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_I6z69oFMEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_I6z694FMEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_I6z69IFMEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_I6z69YFMEe2uhP38WPXKYg" points="[-22, -28, -1, 145]$[-22, -143, -1, 30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_I60iAIFMEe2uhP38WPXKYg" id="(1.0,0.6511627906976745)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_KRbIk4FMEe2uhP38WPXKYg" type="4001" element="_KRbIkIFMEe2uhP38WPXKYg" source="_F__voIFMEe2uhP38WPXKYg" target="_H3omtIFMEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_KRbvoIFMEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_KRbvoYFMEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_KRbIlIFMEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_KRbIlYFMEe2uhP38WPXKYg" points="[-14, -31, 54, 126]$[-68, -143, 0, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_KRbvooFMEe2uhP38WPXKYg" id="(1.0,0.5166666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RRkKg4FMEe2uhP38WPXKYg" type="4001" element="_RRkKgIFMEe2uhP38WPXKYg" source="_Bs3GhIFMEe2uhP38WPXKYg" target="_OayxuYFMEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_RRkKhoFMEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RRkxkIFMEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RRkKhIFMEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RRkKhYFMEe2uhP38WPXKYg" points="[0, -10, -244, -19]$[184, -10, -60, -19]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_RRkxkYFMEe2uhP38WPXKYg" id="(1.0,0.7209302325581395)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SC9yQIFMEe2uhP38WPXKYg" type="4001" element="_SC9LMIFMEe2uhP38WPXKYg" source="_OayxuYFMEe2uhP38WPXKYg" target="_QQu_pIFMEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_SC9yQ4FMEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SC9yRIFMEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SC9yQYFMEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SC9yQoFMEe2uhP38WPXKYg" points="[-17, 29, 43, -87]$[-65, 101, -5, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_SC-ZUIFMEe2uhP38WPXKYg" id="(1.0,0.5166666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_lYnYU4FMEe2uhP38WPXKYg" type="4001" element="_lYnYUIFMEe2uhP38WPXKYg" source="__8D3RIFLEe2uhP38WPXKYg" target="_WFa7EIFMEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_lYnYVoFMEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_lYnYV4FMEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_lYnYVIFMEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_lYnYVYFMEe2uhP38WPXKYg" points="[0, -2, 21, -177]$[-19, 205, 2, 30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_lYn_YIFMEe2uhP38WPXKYg" id="(1.0,0.5348837209302325)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_nJ5Is4FMEe2uhP38WPXKYg" type="4001" element="_nJ5IsIFMEe2uhP38WPXKYg" source="_Bs3GhIFMEe2uhP38WPXKYg" target="_dvJsmYFMEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_nJ5ItoFMEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_nJ5vwIFMEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_nJ5ItIFMEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_nJ5ItYFMEe2uhP38WPXKYg" points="[-22, 16, -11, -316]$[-22, 297, -11, -35]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_nJ6W0IFMEe2uhP38WPXKYg" id="(1.0,0.627906976744186)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_oFUPIIFMEe2uhP38WPXKYg" type="4001" element="_oFToEIFMEe2uhP38WPXKYg" source="_ZNXjcIFMEe2uhP38WPXKYg" target="_dvJsmYFMEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_oFUPI4FMEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_oFUPJIFMEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_oFUPIYFMEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_oFUPIoFMEe2uhP38WPXKYg" points="[0, -6, -273, 5]$[130, -6, -143, 5]$[130, -11, -143, 0]$[260, -11, -13, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_oFU2MIFMEe2uhP38WPXKYg" id="(1.0,0.6)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_oFU2MYFMEe2uhP38WPXKYg" id="(0.09285714285714286,0.5571428571428572)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_saVuoIFMEe2uhP38WPXKYg" type="4001" element="_saVHkIFMEe2uhP38WPXKYg" source="_WFa7EIFMEe2uhP38WPXKYg" target="_ZNXjcIFMEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_saVuo4FMEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_saVupIFMEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_saVuoYFMEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_saVuooFMEe2uhP38WPXKYg" points="[-14, 38, 45, -117]$[-51, 130, 8, -25]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_saWVsIFMEe2uhP38WPXKYg" id="(1.0,0.36666666666666664)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_vk60Q4FMEe2uhP38WPXKYg" type="4001" element="_vk60QIFMEe2uhP38WPXKYg" source="_ZNXjcIFMEe2uhP38WPXKYg" target="_h7BQGIFMEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_vk60RoFMEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_vk60R4FMEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_vk60RIFMEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_vk60RYFMEe2uhP38WPXKYg" points="[-100, -5, 224, 10]$[-296, -17, 28, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_vk7bUIFMEe2uhP38WPXKYg" id="(1.0,0.56)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_vk7bUYFMEe2uhP38WPXKYg" id="(0.8,0.4714285714285714)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_x8E444FMEe2uhP38WPXKYg" type="4001" element="_x8E44IFMEe2uhP38WPXKYg" source="_67qfgIFLEe2uhP38WPXKYg" target="_h7BQGIFMEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_x8Ff8IFMEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_x8Ff8YFMEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_x8E45IFMEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_x8E45YFMEe2uhP38WPXKYg" points="[-7, 32, 63, -295]$[-67, 292, 3, -35]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_x8GHAIFMEe2uhP38WPXKYg" id="(1.0,0.4666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IeybY4FOEe2uhP38WPXKYg" type="4001" element="_IeybYIFOEe2uhP38WPXKYg" source="_dvJsmYFMEe2uhP38WPXKYg" target="_46OhV4FNEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IeybZoFOEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IeybZ4FOEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IeybZIFOEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IeybZYFOEe2uhP38WPXKYg" points="[-10, 40, 60, -145]$[0, 182, 70, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IezCcIFOEe2uhP38WPXKYg" id="(1.0,0.42857142857142855)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_JHTz8oFOEe2uhP38WPXKYg" type="4001" element="_JHTM4IFOEe2uhP38WPXKYg" source="_h7BQGIFMEe2uhP38WPXKYg" target="_EKZOBIFOEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_JHTz9YFOEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_JHTz9oFOEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_JHTz84FOEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JHTz9IFOEe2uhP38WPXKYg" points="[-17, 44, 63, -171]$[-80, 207, 0, -8]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_JHUbAIFOEe2uhP38WPXKYg" id="(1.0,0.37142857142857144)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_JHUbAYFOEe2uhP38WPXKYg" id="(0.5116279069767442,0.20930232558139536)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_J7GoY4FOEe2uhP38WPXKYg" type="4001" element="_J7GoYIFOEe2uhP38WPXKYg" source="_EKZOBIFOEe2uhP38WPXKYg" target="_ALH8GYFOEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_J7HPcIFOEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_J7HPcYFOEe2uhP38WPXKYg" x="37"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_J7GoZIFOEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_J7GoZYFOEe2uhP38WPXKYg" points="[-6, 1, -182, -3]$[175, -26, -1, -30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_J7H2gIFOEe2uhP38WPXKYg" id="(1.0,0.6046511627906976)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PRk904FOEe2uhP38WPXKYg" type="4001" element="_PRk90IFOEe2uhP38WPXKYg" source="_EKZOBIFOEe2uhP38WPXKYg" target="_L_3VeIFOEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_PRk91oFOEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PRk914FOEe2uhP38WPXKYg" x="26" y="1"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PRk91IFOEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PRk91YFOEe2uhP38WPXKYg" points="[0, -2, 24, -177]$[-26, 145, -2, -30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_PRlk4IFOEe2uhP38WPXKYg" id="(1.0,0.5348837209302325)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jLNas4FOEe2uhP38WPXKYg" type="4001" element="_jLNasIFOEe2uhP38WPXKYg" source="_ALH8GYFOEe2uhP38WPXKYg" target="_dZyOoIFOEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jLNatoFOEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jLNat4FOEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jLNatIFOEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jLNatYFOEe2uhP38WPXKYg" points="[-5, 30, 35, -170]$[-35, 240, 5, 40]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_jLOBwIFOEe2uhP38WPXKYg" id="(1.0,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_o8byc4FOEe2uhP38WPXKYg" type="4001" element="_o8bycIFOEe2uhP38WPXKYg" source="_46OhV4FNEe2uhP38WPXKYg" target="_lEc0SYFOEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_o8cZgIFOEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_o8cZgYFOEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_o8bydIFOEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_o8bydYFOEe2uhP38WPXKYg" points="[-14, 42, 56, -142]$[-10, 180, 60, -4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_o8dAkIFOEe2uhP38WPXKYg" id="(1.0,0.4)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_yizPwIFOEe2uhP38WPXKYg" type="4001" element="_yiyosIFOEe2uhP38WPXKYg" source="_L_3VeIFOEe2uhP38WPXKYg" target="_r0fksIFOEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_yizPw4FOEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_yizPxIFOEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_yizPwYFOEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_yizPwoFOEe2uhP38WPXKYg" points="[-9, 32, 51, -130]$[0, 167, 60, 5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_yiz20IFOEe2uhP38WPXKYg" id="(1.0,0.4666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_yy2d8oFOEe2uhP38WPXKYg" type="4001" element="_yy124IFOEe2uhP38WPXKYg" source="_r0fksIFOEe2uhP38WPXKYg" target="_u_-CM4FOEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_yy2d9YFOEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_yy2d9oFOEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_yy2d84FOEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_yy2d9IFOEe2uhP38WPXKYg" points="[-15, 31, 39, -91]$[-57, 136, -3, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_yy3FAIFOEe2uhP38WPXKYg" id="(1.0,0.48333333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_zEV2koFOEe2uhP38WPXKYg" type="4001" element="_zEVPgIFOEe2uhP38WPXKYg" source="_dZyOoIFOEe2uhP38WPXKYg" target="_vWnAkIFOEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_zEV2lYFOEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_zEV2loFOEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_zEV2k4FOEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_zEV2lIFOEe2uhP38WPXKYg" points="[-23, 53, 45, -108]$[-69, 166, -1, 5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_zEWdoIFOEe2uhP38WPXKYg" id="(1.0,0.3375)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_zEWdoYFOEe2uhP38WPXKYg" id="(0.4666666666666667,0.8)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_zZgOQIFOEe2uhP38WPXKYg" type="4001" element="_zZfnMIFOEe2uhP38WPXKYg" source="_lEc0SYFOEe2uhP38WPXKYg" target="_vm1N44FOEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_zZgOQ4FOEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_zZgORIFOEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_zZgOQYFOEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_zZgOQoFOEe2uhP38WPXKYg" points="[-8, 31, 27, -116]$[-37, 132, -2, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_zZg1UIFOEe2uhP38WPXKYg" id="(1.0,0.48333333333333334)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
