<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_WsrsAIEjEe2uhP38WPXKYg" name=" Poliklinik Hizmetleri Süreci" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_WsrsAYEjEe2uhP38WPXKYg" name="Pool">
      <elements xmi:type="process:Lane" xmi:id="_WsrsAoEjEe2uhP38WPXKYg" name="Employee lane" actor="_WsrsG4EjEe2uhP38WPXKYg">
        <elements xmi:type="process:StartEvent" xmi:id="_WsrsA4EjEe2uhP38WPXKYg" name="Başla" outgoing="_WsrsGIEjEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_WsrsBIEjEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_WsrsBYEjEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_WsrsBoEjEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_WsrsB4EjEe2uhP38WPXKYg" name="Hastanın muayne isteği" outgoing="_idlQwIEvEe2uhP38WPXKYg" incoming="_WsrsGIEjEe2uhP38WPXKYg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_WsrsCIEjEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_WsrsCYEjEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_WsrsCoEjEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_WsrsC4EjEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_WsrsDIEjEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_WsrsDYEjEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_WsrsDoEjEe2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_WsrsD4EjEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_WsrsEIEjEe2uhP38WPXKYg">
            <targetForm xmi:type="expression:Expression" xmi:id="_WsrsEYEjEe2uhP38WPXKYg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_WsrsEoEjEe2uhP38WPXKYg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_WsrsE4EjEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_M9zK4IEuEe2uhP38WPXKYg" name="İşlemlerin ücretli olarak yapılması" outgoing="_rWE7cIEvEe2uhP38WPXKYg" incoming="_i8CHUIEvEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_M9zK4oEuEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_M9zK4YEuEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_M9zK44EuEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_M9zK5IEuEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_M9zK5YEuEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_M9zK5oEuEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_M9zK6IEuEe2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_M9zK54EuEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ReceiveTask" xmi:id="_IIS_EIEvEe2uhP38WPXKYg" name="Sekreter tarafından poliklinik kayıtlarının yapılması" outgoing="_soEu0IEvEe2uhP38WPXKYg" incoming="_j648QIEvEe2uhP38WPXKYg _rWE7cIEvEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_IIS_EoEvEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_IIS_EYEvEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_IIS_E4EvEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_IIS_FIEvEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_IIS_FYEvEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_IIS_FoEvEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_IIS_GIEvEe2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_IIS_F4EvEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:InclusiveGateway" xmi:id="_e8aQEIEvEe2uhP38WPXKYg" name="Hastanın sosyal güvencesi var mı ?" outgoing="_i8CHUIEvEe2uhP38WPXKYg _j648QIEvEe2uhP38WPXKYg" incoming="_idlQwIEvEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_e8aQEoEvEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_e8aQEYEvEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_e8aQE4EvEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_nm8-UIEvEe2uhP38WPXKYg" name="Doktor tarafından muaynenin yapılması" outgoing="_Jt7t4IE0Ee2uhP38WPXKYg" incoming="_soEu0IEvEe2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_nm8-UoEvEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_nm8-UYEvEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_nm8-U4EvEe2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_nm8-VIEvEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_nm8-VYEvEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_nm8-VoEvEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_nm8-WIEvEe2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_nm8-V4EvEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:InclusiveGateway" xmi:id="_GTMsYIE0Ee2uhP38WPXKYg" name="Tetkik gerekiyor mu ?" outgoing="_SucFEIE0Ee2uhP38WPXKYg _PTEDAIE3Ee2uhP38WPXKYg" incoming="_Jt7t4IE0Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_GTMsYoE0Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_GTMsYYE0Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_GTMsY4E0Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:InclusiveGateway" xmi:id="_OqgVkIE0Ee2uhP38WPXKYg" name="Tetkikler hastanenin imkanları ile yapılabilir mi ?" outgoing="_nXMRwIE0Ee2uhP38WPXKYg _YzdGEIE1Ee2uhP38WPXKYg" incoming="_SucFEIE0Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_OqgVkoE0Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_OqgVkYE0Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_OqgVk4E0Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_jO0uMIE0Ee2uhP38WPXKYg" name="Dış tetkik istem forumu ile istem yapılması" outgoing="_1xTK4IE0Ee2uhP38WPXKYg" incoming="_nXMRwIE0Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jO1VQYE0Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jO1VQIE0Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jO1VQoE0Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_jO1VQ4E0Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_jO1VRIE0Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_jO1VRYE0Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_jO1VR4E0Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_jO1VRoE0Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_rO0qoIE0Ee2uhP38WPXKYg" name="Anlaşmalı laboratuarda tetkikin yapılması" outgoing="_2yGrIIE1Ee2uhP38WPXKYg" incoming="_1xTK4IE0Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_rO0qooE0Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_rO0qoYE0Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_rO0qo4E0Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_rO0qpIE0Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_rO0qpYE0Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_rO1RsIE0Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_rO1RsoE0Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_rO1RsYE0Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_V-wJ0IE1Ee2uhP38WPXKYg" name="Tetkiklerin yapılması" outgoing="_0_DZIIE1Ee2uhP38WPXKYg" incoming="_YzdGEIE1Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_V-wJ0oE1Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_V-wJ0YE1Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_V-wJ04E1Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_V-wJ1IE1Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_V-wJ1YE1Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_V-wJ1oE1Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_V-wJ2IE1Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_V-wJ14E1Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_yIVDoIE1Ee2uhP38WPXKYg" name="Hastaya tedavi yönteminin belirlenmesi" outgoing="_A_ly0IE2Ee2uhP38WPXKYg" incoming="_0_DZIIE1Ee2uhP38WPXKYg _2yGrIIE1Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_yIVqsYE1Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_yIVqsIE1Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_yIVqsoE1Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_yIVqs4E1Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_yIVqtIE1Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_yIVqtYE1Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_yIVqt4E1Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_yIVqtoE1Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_-nvxsIE1Ee2uhP38WPXKYg" name="Tedavi sürecinin başlatılması" outgoing="_G8ICsIE2Ee2uhP38WPXKYg" incoming="_A_ly0IE2Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_-nwYwYE1Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_-nwYwIE1Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_-nwYwoE1Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_-nwYw4E1Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_-nwYxIE1Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_-nwYxYE1Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_-nwYx4E1Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_-nwYxoE1Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:InclusiveGateway" xmi:id="_DZAhQIE2Ee2uhP38WPXKYg" name="Sonuç" outgoing="_NX2I8IE2Ee2uhP38WPXKYg _WcR94IE2Ee2uhP38WPXKYg _biXt8IE2Ee2uhP38WPXKYg" incoming="_G8ICsIE2Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_DZAhQoE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_DZAhQYE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_DZAhQ4E2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_KkuhEIE2Ee2uhP38WPXKYg" name="Defin işlemlerinin yapılması" outgoing="_QumpYIE2Ee2uhP38WPXKYg" incoming="_NX2I8IE2Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_KkuhEoE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_KkuhEYE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_KkuhE4E2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_KkuhFIE2Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_KkuhFYE2Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_KkuhFoE2Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_KkuhGIE2Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_KkuhF4E2Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_PTgkYIE2Ee2uhP38WPXKYg" name="İşlem sonu" incoming="_QumpYIE2Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PThLcYE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PThLcIE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PThLcoE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:InclusiveGateway" xmi:id="_SbwHsIE2Ee2uhP38WPXKYg" name="Sonuç" outgoing="_Wx1-MIE2Ee2uhP38WPXKYg _KxgjYIE3Ee2uhP38WPXKYg" incoming="_WcR94IE2Ee2uhP38WPXKYg _PTEDAIE3Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SbxV0YE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SbxV0IE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SbxV0oE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:InclusiveGateway" xmi:id="_SzSd8IE2Ee2uhP38WPXKYg" name="Sonuç" outgoing="_XGweQIE2Ee2uhP38WPXKYg _LXOfkIE3Ee2uhP38WPXKYg _8J3IEIE3Ee2uhP38WPXKYg" incoming="_Wx1-MIE2Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SzSd8oE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SzSd8YE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SzSd84E2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:InclusiveGateway" xmi:id="_TGz24IE2Ee2uhP38WPXKYg" name="Sonuç" outgoing="_Lz0U8IE3Ee2uhP38WPXKYg __rATkIE3Ee2uhP38WPXKYg" incoming="_XGweQIE2Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_TGz24oE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_TGz24YE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_TGz244E2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_YL2eEIE2Ee2uhP38WPXKYg" name="Yatış işlemlerinin yapılması" outgoing="_HJFEIIE3Ee2uhP38WPXKYg" incoming="_biXt8IE2Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_YL3FIYE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_YL3FIIE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_YL3FIoE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_YL3FI4E2Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_YL3FJIE2Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_YL3FJYE2Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_YL3FJ4E2Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_YL3FJoE2Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_vaYaMIE2Ee2uhP38WPXKYg" name="İşlem sonu" incoming="_HJFEIIE3Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_vaZBQYE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_vaZBQIE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_vaZBQoE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_wnH6IIE2Ee2uhP38WPXKYg" name="İşlem sonu" incoming="_Hid0gIE3Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_wnH6IoE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_wnH6IYE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_wnH6I4E2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_yI85QIE2Ee2uhP38WPXKYg" name="İşlem sonu" incoming="_H4RscIE3Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_yI85QoE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_yI85QYE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_yI85Q4E2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_yzsfYIE2Ee2uhP38WPXKYg" name="İşlem sonu" incoming="_IJG9wIE3Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_yztGcYE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_yztGcIE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_yztGcoE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_5xYqQIE2Ee2uhP38WPXKYg" name="Yatış işlemlerinin başlatılması" outgoing="_Hid0gIE3Ee2uhP38WPXKYg" incoming="_KxgjYIE3Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5xZRUYE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5xZRUIE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5xZRUoE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_5xZRU4E2Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_5xZRVIE2Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_5xZRVYE2Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_5xZRV4E2Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_5xZRVoE2Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ReceiveTask" xmi:id="_9fnPgIE2Ee2uhP38WPXKYg" name="Doktor tarafından reçete yazılması" outgoing="_H4RscIE3Ee2uhP38WPXKYg" incoming="_LXOfkIE3Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_9fn2kYE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_9fn2kIE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_9fn2koE2Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_9fn2k4E2Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_9fn2lIE2Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_9fn2lYE2Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_9fn2l4E2Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_9fn2loE2Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_CvXR4IE3Ee2uhP38WPXKYg" name="Çıkış işlemlerinin yapılması" outgoing="_IJG9wIE3Ee2uhP38WPXKYg" incoming="_Lz0U8IE3Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_CvX48YE3Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_CvX48IE3Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_CvX48oE3Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_CvX484E3Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_CvX49IE3Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_CvX49YE3Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_CvX494E3Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_CvX49oE3Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_eoxBsIE3Ee2uhP38WPXKYg" name="Sevk işlemlerinin yapılması" outgoing="_-pnvEIE3Ee2uhP38WPXKYg" incoming="_8J3IEIE3Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_eoxBsoE3Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_eoxBsYE3Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_eoxBs4E3Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_eoxBtIE3Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_eoxBtYE3Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_eoxBtoE3Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_eoxBuIE3Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_eoxBt4E3Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_fCqvcIE3Ee2uhP38WPXKYg" name="Hatane üst yönetiminin onayının alınması" outgoing="__DJpYIE3Ee2uhP38WPXKYg" incoming="_-pnvEIE3Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_fCqvcoE3Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_fCqvcYE3Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_fCqvc4E3Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_fCqvdIE3Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_fCqvdYE3Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_fCqvdoE3Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_fCqveIE3Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_fCqvd4E3Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_fkiGYIE3Ee2uhP38WPXKYg" name="Sevk işlemlerinin yapılması" outgoing="____FEIE3Ee2uhP38WPXKYg" incoming="__rATkIE3Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_fkiGYoE3Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_fkiGYYE3Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_fkiGY4E3Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_fkiGZIE3Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_fkiGZYE3Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_fkiGZoE3Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_fkiGaIE3Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_fkiGZ4E3Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_gTKG8IE3Ee2uhP38WPXKYg" name="İşlem sonu" incoming="__DJpYIE3Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_gTKG8oE3Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_gTKG8YE3Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_gTKG84E3Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_g_Pw4IE3Ee2uhP38WPXKYg" name="İşlem sonu" incoming="____FEIE3Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_g_Pw4oE3Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_g_Pw4YE3Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_g_Pw44E3Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_WsrsFIEjEe2uhP38WPXKYg">
        <targetForm xmi:type="expression:Expression" xmi:id="_WsrsFYEjEe2uhP38WPXKYg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_WsrsFoEjEe2uhP38WPXKYg">
        <targetForm xmi:type="expression:Expression" xmi:id="_WsrsF4EjEe2uhP38WPXKYg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_WsrsGIEjEe2uhP38WPXKYg" target="_WsrsB4EjEe2uhP38WPXKYg" source="_WsrsA4EjEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_WsrsGYEjEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_WsrsGoEjEe2uhP38WPXKYg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_idlQwIEvEe2uhP38WPXKYg" target="_e8aQEIEvEe2uhP38WPXKYg" source="_WsrsB4EjEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_idlQwYEvEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_idlQwoEvEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_i8CHUIEvEe2uhP38WPXKYg" name="Hayır" target="_M9zK4IEuEe2uhP38WPXKYg" source="_e8aQEIEvEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_i8CHUYEvEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_i8CHUoEvEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_j648QIEvEe2uhP38WPXKYg" name="Evet" target="_IIS_EIEvEe2uhP38WPXKYg" source="_e8aQEIEvEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_j648QYEvEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_j648QoEvEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_rWE7cIEvEe2uhP38WPXKYg" target="_IIS_EIEvEe2uhP38WPXKYg" source="_M9zK4IEuEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_rWE7cYEvEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_rWE7coEvEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_soEu0IEvEe2uhP38WPXKYg" target="_nm8-UIEvEe2uhP38WPXKYg" source="_IIS_EIEvEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_soEu0YEvEe2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_soEu0oEvEe2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Jt7t4IE0Ee2uhP38WPXKYg" target="_GTMsYIE0Ee2uhP38WPXKYg" source="_nm8-UIEvEe2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Jt7t4YE0Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_Jt7t4oE0Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SucFEIE0Ee2uhP38WPXKYg" name="Evet" target="_OqgVkIE0Ee2uhP38WPXKYg" source="_GTMsYIE0Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SucFEYE0Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_SucFEoE0Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_nXMRwIE0Ee2uhP38WPXKYg" name="Hayır" target="_jO0uMIE0Ee2uhP38WPXKYg" source="_OqgVkIE0Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_nXMRwYE0Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_nXMRwoE0Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1xTK4IE0Ee2uhP38WPXKYg" target="_rO0qoIE0Ee2uhP38WPXKYg" source="_jO0uMIE0Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1xTx8IE0Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_1xTx8YE0Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_YzdGEIE1Ee2uhP38WPXKYg" target="_V-wJ0IE1Ee2uhP38WPXKYg" source="_OqgVkIE0Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_YzdtIIE1Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_YzdtIYE1Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0_DZIIE1Ee2uhP38WPXKYg" target="_yIVDoIE1Ee2uhP38WPXKYg" source="_V-wJ0IE1Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0_DZIYE1Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_0_DZIoE1Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2yGrIIE1Ee2uhP38WPXKYg" target="_yIVDoIE1Ee2uhP38WPXKYg" source="_rO0qoIE0Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2yGrIYE1Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_2yGrIoE1Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_A_ly0IE2Ee2uhP38WPXKYg" target="_-nvxsIE1Ee2uhP38WPXKYg" source="_yIVDoIE1Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_A_ly0YE2Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_A_ly0oE2Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_G8ICsIE2Ee2uhP38WPXKYg" target="_DZAhQIE2Ee2uhP38WPXKYg" source="_-nvxsIE1Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_G8ICsYE2Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_G8ICsoE2Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_NX2I8IE2Ee2uhP38WPXKYg" name="Ölüm" target="_KkuhEIE2Ee2uhP38WPXKYg" source="_DZAhQIE2Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_NX2wAIE2Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_NX2wAYE2Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_QumpYIE2Ee2uhP38WPXKYg" target="_PTgkYIE2Ee2uhP38WPXKYg" source="_KkuhEIE2Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_QunQcIE2Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_QunQcYE2Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_WcR94IE2Ee2uhP38WPXKYg" target="_SbwHsIE2Ee2uhP38WPXKYg" source="_DZAhQIE2Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_WcR94YE2Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_WcR94oE2Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Wx1-MIE2Ee2uhP38WPXKYg" target="_SzSd8IE2Ee2uhP38WPXKYg" source="_SbwHsIE2Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Wx1-MYE2Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_Wx1-MoE2Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_XGweQIE2Ee2uhP38WPXKYg" target="_TGz24IE2Ee2uhP38WPXKYg" source="_SzSd8IE2Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_XGweQYE2Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_XGweQoE2Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_biXt8IE2Ee2uhP38WPXKYg" name="Hastanede tedavi" target="_YL2eEIE2Ee2uhP38WPXKYg" source="_DZAhQIE2Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_biXt8YE2Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_biXt8oE2Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_HJFEIIE3Ee2uhP38WPXKYg" target="_vaYaMIE2Ee2uhP38WPXKYg" source="_YL2eEIE2Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_HJFEIYE3Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_HJFEIoE3Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Hid0gIE3Ee2uhP38WPXKYg" target="_wnH6IIE2Ee2uhP38WPXKYg" source="_5xYqQIE2Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Hid0gYE3Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_HiebkIE3Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_H4RscIE3Ee2uhP38WPXKYg" target="_yI85QIE2Ee2uhP38WPXKYg" source="_9fnPgIE2Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_H4RscYE3Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_H4RscoE3Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IJG9wIE3Ee2uhP38WPXKYg" target="_yzsfYIE2Ee2uhP38WPXKYg" source="_CvXR4IE3Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IJG9wYE3Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_IJG9woE3Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_KxgjYIE3Ee2uhP38WPXKYg" name="Ameliyat" target="_5xYqQIE2Ee2uhP38WPXKYg" source="_SbwHsIE2Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_KxhxgIE3Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_KxhxgYE3Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_LXOfkIE3Ee2uhP38WPXKYg" name="İlaçla tedavi" target="_9fnPgIE2Ee2uhP38WPXKYg" source="_SzSd8IE2Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_LXOfkYE3Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_LXOfkoE3Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Lz0U8IE3Ee2uhP38WPXKYg" name="Tedaviye ihtiyaç görülmemesi" target="_CvXR4IE3Ee2uhP38WPXKYg" source="_TGz24IE2Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Lz0U8YE3Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_Lz0U8oE3Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PTEDAIE3Ee2uhP38WPXKYg" target="_SbwHsIE2Ee2uhP38WPXKYg" source="_GTMsYIE0Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PTEDAYE3Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_PTEDAoE3Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8J3IEIE3Ee2uhP38WPXKYg" name="Başka kuruma sevk" target="_eoxBsIE3Ee2uhP38WPXKYg" source="_SzSd8IE2Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8J3IEYE3Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_8J3IEoE3Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_-pnvEIE3Ee2uhP38WPXKYg" target="_fCqvcIE3Ee2uhP38WPXKYg" source="_eoxBsIE3Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_-pnvEYE3Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_-pnvEoE3Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__DJpYIE3Ee2uhP38WPXKYg" target="_gTKG8IE3Ee2uhP38WPXKYg" source="_fCqvcIE3Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__DJpYYE3Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="__DJpYoE3Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__rATkIE3Ee2uhP38WPXKYg" name="Başka polikliniğe sevk" target="_fkiGYIE3Ee2uhP38WPXKYg" source="_TGz24IE2Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__rATkYE3Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="__rATkoE3Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="____FEIE3Ee2uhP38WPXKYg" target="_g_Pw4IE3Ee2uhP38WPXKYg" source="_fkiGYIE3Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="____FEYE3Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="____FEoE3Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_WsrsG4EjEe2uhP38WPXKYg" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_WsrsHIEjEe2uhP38WPXKYg"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_WsrsHYEjEe2uhP38WPXKYg">
        <name xmi:type="expression:Expression" xmi:id="_WsrsHoEjEe2uhP38WPXKYg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_WsrsH4EjEe2uhP38WPXKYg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_WsrsIIEjEe2uhP38WPXKYg">
        <name xmi:type="expression:Expression" xmi:id="_WsrsIYEjEe2uhP38WPXKYg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_WsrsIoEjEe2uhP38WPXKYg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_WsrsI4EjEe2uhP38WPXKYg">
        <name xmi:type="expression:Expression" xmi:id="_WsrsJIEjEe2uhP38WPXKYg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_WsrsJYEjEe2uhP38WPXKYg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_WsrsJoEjEe2uhP38WPXKYg">
        <name xmi:type="expression:Expression" xmi:id="_WsrsJ4EjEe2uhP38WPXKYg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_WsrsKIEjEe2uhP38WPXKYg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_WsrsKYEjEe2uhP38WPXKYg">
        <name xmi:type="expression:Expression" xmi:id="_WsrsKoEjEe2uhP38WPXKYg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_WsrsK4EjEe2uhP38WPXKYg" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_WsrsLIEjEe2uhP38WPXKYg" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_WsrsLYEjEe2uhP38WPXKYg" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_WsrsLoEjEe2uhP38WPXKYg" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_WsrsL4EjEe2uhP38WPXKYg" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_WsrsMIEjEe2uhP38WPXKYg" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_WsrsMYEjEe2uhP38WPXKYg" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_WsrsMoEjEe2uhP38WPXKYg" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_WsrsM4EjEe2uhP38WPXKYg" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_WsrsNIEjEe2uhP38WPXKYg" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_WsrsNYEjEe2uhP38WPXKYg" type="Process" element="_WsrsAIEjEe2uhP38WPXKYg" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_WsrsNoEjEe2uhP38WPXKYg" type="2007" element="_WsrsAYEjEe2uhP38WPXKYg">
      <children xmi:type="notation:DecorationNode" xmi:id="_WsrsN4EjEe2uhP38WPXKYg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_WsrsOIEjEe2uhP38WPXKYg" type="7001">
        <children xmi:type="notation:Node" xmi:id="_WsrsOYEjEe2uhP38WPXKYg" type="3007" element="_WsrsAoEjEe2uhP38WPXKYg">
          <children xmi:type="notation:DecorationNode" xmi:id="_WsrsOoEjEe2uhP38WPXKYg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_WsrsO4EjEe2uhP38WPXKYg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_WsrsPIEjEe2uhP38WPXKYg" type="3005" element="_WsrsB4EjEe2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_WsrsPYEjEe2uhP38WPXKYg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_WsrsPoEjEe2uhP38WPXKYg" x="160" y="68" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_WsrsP4EjEe2uhP38WPXKYg" type="3002" element="_WsrsA4EjEe2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_WsrsQIEjEe2uhP38WPXKYg" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_WsrsQYEjEe2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_WsrsQoEjEe2uhP38WPXKYg" x="60" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_M9zK6YEuEe2uhP38WPXKYg" type="3006" element="_M9zK4IEuEe2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_M91nIIEuEe2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_M9zK6oEuEe2uhP38WPXKYg" x="734" y="66" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_IIVbUIEvEe2uhP38WPXKYg" type="3026" element="_IIS_EIEvEe2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_IIVbUoEvEe2uhP38WPXKYg" type="5012"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IIVbUYEvEe2uhP38WPXKYg" x="420" y="218" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_e8csUIEvEe2uhP38WPXKYg" type="3051" element="_e8aQEIEvEe2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_e8csUoEvEe2uhP38WPXKYg" type="5075">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_e8csU4EvEe2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_e8csUYEvEe2uhP38WPXKYg" x="479" y="61"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_nm8-WYEvEe2uhP38WPXKYg" type="3006" element="_nm8-UIEvEe2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_nm_akIEvEe2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_nm8-WoEvEe2uhP38WPXKYg" x="430" y="330" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_GTNTcIE0Ee2uhP38WPXKYg" type="3051" element="_GTMsYIE0Ee2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_GTNTcoE0Ee2uhP38WPXKYg" type="5075">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_GTNTc4E0Ee2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GTNTcYE0Ee2uhP38WPXKYg" x="517" y="445"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Oqg8oIE0Ee2uhP38WPXKYg" type="3051" element="_OqgVkIE0Ee2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Oqg8ooE0Ee2uhP38WPXKYg" type="5075">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Oqg8o4E0Ee2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Oqg8oYE0Ee2uhP38WPXKYg" x="297" y="446"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_jO18UIE0Ee2uhP38WPXKYg" type="3006" element="_jO0uMIE0Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_jO18UoE0Ee2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jO18UYE0Ee2uhP38WPXKYg" x="274" y="299"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_rO1Rs4E0Ee2uhP38WPXKYg" type="3006" element="_rO0qoIE0Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_rO14wIE0Ee2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_rO1RtIE0Ee2uhP38WPXKYg" x="53" y="288" width="144" height="72"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_V-ww4IE1Ee2uhP38WPXKYg" type="3006" element="_V-wJ0IE1Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_V-ww4oE1Ee2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_V-ww4YE1Ee2uhP38WPXKYg" x="109" y="426"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_yIVquIE1Ee2uhP38WPXKYg" type="3006" element="_yIVDoIE1Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_yIWRwIE1Ee2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yIVquYE1Ee2uhP38WPXKYg" x="62" y="666" width="126" height="63"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_-nwYyIE1Ee2uhP38WPXKYg" type="3006" element="_-nvxsIE1Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_-nwYyoE1Ee2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-nwYyYE1Ee2uhP38WPXKYg" x="53" y="858" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_DZAhRIE2Ee2uhP38WPXKYg" type="3051" element="_DZAhQIE2Ee2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_DZBIUIE2Ee2uhP38WPXKYg" type="5075">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_DZBIUYE2Ee2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_DZAhRYE2Ee2uhP38WPXKYg" x="279" y="866"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_KkuhGYE2Ee2uhP38WPXKYg" type="3006" element="_KkuhEIE2Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_KkvIIIE2Ee2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_KkuhGoE2Ee2uhP38WPXKYg" x="230" y="690" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PThLc4E2Ee2uhP38WPXKYg" type="3003" element="_PTgkYIE2Ee2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_PThLdYE2Ee2uhP38WPXKYg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_PThLdoE2Ee2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PThLdIE2Ee2uhP38WPXKYg" x="286" y="552"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Sbx84IE2Ee2uhP38WPXKYg" type="3051" element="_SbwHsIE2Ee2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Sbx84oE2Ee2uhP38WPXKYg" type="5075">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Sbx844E2Ee2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Sbx84YE2Ee2uhP38WPXKYg" x="517" y="875"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SzSd9IE2Ee2uhP38WPXKYg" type="3051" element="_SzSd8IE2Ee2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_SzTFAIE2Ee2uhP38WPXKYg" type="5075">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_SzTFAYE2Ee2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SzSd9YE2Ee2uhP38WPXKYg" x="782" y="866"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_TG0d8IE2Ee2uhP38WPXKYg" type="3051" element="_TGz24IE2Ee2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_TG0d8oE2Ee2uhP38WPXKYg" type="5075">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_TG0d84E2Ee2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TG0d8YE2Ee2uhP38WPXKYg" x="998" y="866"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_YL3FKIE2Ee2uhP38WPXKYg" type="3006" element="_YL2eEIE2Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_YL3FKoE2Ee2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_YL3FKYE2Ee2uhP38WPXKYg" x="241" y="1032" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_vaZBQ4E2Ee2uhP38WPXKYg" type="3003" element="_vaYaMIE2Ee2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_vaZBRYE2Ee2uhP38WPXKYg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_vaZBRoE2Ee2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vaZBRIE2Ee2uhP38WPXKYg" x="292" y="1156"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_wnH6JIE2Ee2uhP38WPXKYg" type="3003" element="_wnH6IIE2Ee2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_wnH6JoE2Ee2uhP38WPXKYg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_wnH6J4E2Ee2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wnH6JYE2Ee2uhP38WPXKYg" x="524" y="1156"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_yI9gUIE2Ee2uhP38WPXKYg" type="3003" element="_yI85QIE2Ee2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_yI9gUoE2Ee2uhP38WPXKYg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_yI9gU4E2Ee2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yI9gUYE2Ee2uhP38WPXKYg" x="795" y="1156"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_yztGc4E2Ee2uhP38WPXKYg" type="3003" element="_yzsfYIE2Ee2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_yztGdYE2Ee2uhP38WPXKYg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_yztGdoE2Ee2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yztGdIE2Ee2uhP38WPXKYg" x="1005" y="1156"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_5xZRWIE2Ee2uhP38WPXKYg" type="3006" element="_5xYqQIE2Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_5xZRWoE2Ee2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5xZRWYE2Ee2uhP38WPXKYg" x="479" y="1032" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_9fn2mIE2Ee2uhP38WPXKYg" type="3026" element="_9fnPgIE2Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_9fn2moE2Ee2uhP38WPXKYg" type="5012"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_9fn2mYE2Ee2uhP38WPXKYg" x="744" y="1032" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_CvYgAIE3Ee2uhP38WPXKYg" type="3006" element="_CvXR4IE3Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_CvYgAoE3Ee2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_CvYgAYE3Ee2uhP38WPXKYg" x="960" y="1032" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_eoxBuYE3Ee2uhP38WPXKYg" type="3006" element="_eoxBsIE3Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_eoxBu4E3Ee2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eoxBuoE3Ee2uhP38WPXKYg" x="744" y="714" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_fCr9kIE3Ee2uhP38WPXKYg" type="3006" element="_fCqvcIE3Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_fCr9koE3Ee2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fCr9kYE3Ee2uhP38WPXKYg" x="754" y="546" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_fkitcIE3Ee2uhP38WPXKYg" type="3006" element="_fkiGYIE3Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_fkitcoE3Ee2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fkitcYE3Ee2uhP38WPXKYg" x="950" y="690" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_gTKuAIE3Ee2uhP38WPXKYg" type="3003" element="_gTKG8IE3Ee2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_gTKuAoE3Ee2uhP38WPXKYg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_gTKuA4E3Ee2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gTKuAYE3Ee2uhP38WPXKYg" x="810" y="452"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_g_Pw5IE3Ee2uhP38WPXKYg" type="3003" element="_g_Pw4IE3Ee2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_g_QX8IE3Ee2uhP38WPXKYg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_g_QX8YE3Ee2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_g_Pw5YE3Ee2uhP38WPXKYg" x="1005" y="581"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_WsrsQ4EjEe2uhP38WPXKYg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_WsrsRIEjEe2uhP38WPXKYg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_WsrsRYEjEe2uhP38WPXKYg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_WsrsRoEjEe2uhP38WPXKYg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_WsrsR4EjEe2uhP38WPXKYg" x="28" y="10" width="1742" height="1397"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_WsrsSIEjEe2uhP38WPXKYg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_WsrsSYEjEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_WsrsSoEjEe2uhP38WPXKYg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_WsrsS4EjEe2uhP38WPXKYg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_WsrsTIEjEe2uhP38WPXKYg" width="1770" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_WsrsTYEjEe2uhP38WPXKYg"/>
    <edges xmi:type="notation:Connector" xmi:id="_WsrsToEjEe2uhP38WPXKYg" type="4001" element="_WsrsGIEjEe2uhP38WPXKYg" source="_WsrsP4EjEe2uhP38WPXKYg" target="_WsrsPIEjEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_WsrsT4EjEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_WsrsUIEjEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_WsrsUYEjEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_WsrsUoEjEe2uhP38WPXKYg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_idme4IEvEe2uhP38WPXKYg" type="4001" element="_idlQwIEvEe2uhP38WPXKYg" source="_WsrsPIEjEe2uhP38WPXKYg" target="_e8csUIEvEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_idme44EvEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_idme5IEvEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_idme4YEvEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_idme4oEvEe2uhP38WPXKYg" points="[0, 8, -204, -3]$[211, -4, 7, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_idpiMIEvEe2uhP38WPXKYg" id="(1.0,0.5166666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_i8CHU4EvEe2uhP38WPXKYg" type="4001" element="_i8CHUIEvEe2uhP38WPXKYg" source="_e8csUIEvEe2uhP38WPXKYg" target="_M9zK6YEuEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_i8CHVoEvEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_i8CHV4EvEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_i8CHVIEvEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_i8CHVYEvEe2uhP38WPXKYg" points="[-7, 1, -271, 48]$[324, -56, 60, -9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_i8EjkIEvEe2uhP38WPXKYg" id="(1.0,0.6046511627906976)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_j648Q4EvEe2uhP38WPXKYg" type="4001" element="_j648QIEvEe2uhP38WPXKYg" source="_e8csUIEvEe2uhP38WPXKYg" target="_IIVbUIEvEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_j648RoEvEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_j648R4EvEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_j648RIEvEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_j648RYEvEe2uhP38WPXKYg" points="[-23, 9, 6, -162]$[-34, 136, -5, -35]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_j648SIEvEe2uhP38WPXKYg" id="(1.0,0.7674418604651163)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_rWHXsIEvEe2uhP38WPXKYg" type="4001" element="_rWE7cIEvEe2uhP38WPXKYg" source="_M9zK6YEuEe2uhP38WPXKYg" target="_IIVbUIEvEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_rWHXs4EvEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rWHXtIEvEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_rWHXsYEvEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rWHXsoEvEe2uhP38WPXKYg" points="[-54, 35, 249, -164]$[-283, 198, 20, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_rWJz8IEvEe2uhP38WPXKYg" id="(1.0,0.4166666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_rWJz8YEvEe2uhP38WPXKYg" id="(0.8571428571428571,0.4857142857142857)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_soEu04EvEe2uhP38WPXKYg" type="4001" element="_soEu0IEvEe2uhP38WPXKYg" source="_IIVbUIEvEe2uhP38WPXKYg" target="_nm8-WYEvEe2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_soHLEIEvEe2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_soHLEYEvEe2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_soEu1IEvEe2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_soEu1YEvEe2uhP38WPXKYg" points="[-58, 46, 12, -128]$[-58, 144, 12, -30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_soHLEoEvEe2uhP38WPXKYg" id="(1.0,0.34285714285714286)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Jt88AIE0Ee2uhP38WPXKYg" type="4001" element="_Jt7t4IE0Ee2uhP38WPXKYg" source="_nm8-WYEvEe2uhP38WPXKYg" target="_GTNTcIE0Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Jt9jEIE0Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Jt9jEYE0Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Jt88AYE0Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Jt88AoE0Ee2uhP38WPXKYg" points="[-62, 30, 5, -55]$[-62, 51, 5, -34]$[-58, 51, 9, -34]$[-58, 72, 9, -13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Jt-KIIE0Ee2uhP38WPXKYg" id="(1.0,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SucsIIE0Ee2uhP38WPXKYg" type="4001" element="_SucFEIE0Ee2uhP38WPXKYg" source="_GTNTcIE0Ee2uhP38WPXKYg" target="_Oqg8oIE0Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_SucsI4E0Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SucsJIE0Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SucsIYE0Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SucsIoE0Ee2uhP38WPXKYg" points="[-22, -32, 240, -1]$[-242, -32, 20, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_SufIYIE0Ee2uhP38WPXKYg" id="(1.0,0.7441860465116279)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_nXMRw4E0Ee2uhP38WPXKYg" type="4001" element="_nXMRwIE0Ee2uhP38WPXKYg" source="_Oqg8oIE0Ee2uhP38WPXKYg" target="_jO18UIE0Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_nXMRxoE0Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_nXMRx4E0Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_nXMRxIE0Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_nXMRxYE0Ee2uhP38WPXKYg" points="[-2, -6, 14, 49]$[-15, -74, 1, -19]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_nXM40IE0Ee2uhP38WPXKYg" id="(1.0,0.627906976744186)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1xTx8oE0Ee2uhP38WPXKYg" type="4001" element="_1xTK4IE0Ee2uhP38WPXKYg" source="_jO18UIE0Ee2uhP38WPXKYg" target="_rO1Rs4E0Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1xTx9YE0Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1xTx9oE0Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1xTx84E0Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1xTx9IE0Ee2uhP38WPXKYg" points="[-75, 0, 36, 0]$[-93, -4, 18, -4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_1xUZAIE0Ee2uhP38WPXKYg" id="(1.0,0.58)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_1xUZAYE0Ee2uhP38WPXKYg" id="(0.8333333333333334,0.375)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_YzdtIoE1Ee2uhP38WPXKYg" type="4001" element="_YzdGEIE1Ee2uhP38WPXKYg" source="_Oqg8oIE0Ee2uhP38WPXKYg" target="_V-ww4IE1Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_YzdtJYE1Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_YzdtJoE1Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_YzdtI4E1Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_YzdtJIE1Ee2uhP38WPXKYg" points="[-27, -3, 79, 9]$[-97, -14, 9, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Yze7QIE1Ee2uhP38WPXKYg" id="(1.0,0.7674418604651163)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Yze7QYE1Ee2uhP38WPXKYg" id="(0.89,0.4)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0_DZI4E1Ee2uhP38WPXKYg" type="4001" element="_0_DZIIE1Ee2uhP38WPXKYg" source="_V-ww4IE1Ee2uhP38WPXKYg" target="_yIVquIE1Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_0_DZJoE1Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0_DZJ4E1Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0_DZJIE1Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0_DZJYE1Ee2uhP38WPXKYg" points="[-52, 18, 11, -180]$[-52, 82, 11, -116]$[-47, 82, 16, -116]$[-47, 146, 16, -52]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_0_EAMIE1Ee2uhP38WPXKYg" id="(1.0,0.64)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_0_EnQIE1Ee2uhP38WPXKYg" id="(0.42063492063492064,0.8253968253968254)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2yHSMIE1Ee2uhP38WPXKYg" type="4001" element="_2yGrIIE1Ee2uhP38WPXKYg" source="_rO1Rs4E0Ee2uhP38WPXKYg" target="_yIVquIE1Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_2yHSM4E1Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_2yHSNIE1Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_2yHSMYE1Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2yHSMoE1Ee2uhP38WPXKYg" points="[-144, 9, -38, -324]$[-159, 9, -53, -324]$[-159, 175, -53, -158]$[-98, 175, 8, -158]$[-98, 305, 8, -28]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2yIgUIE1Ee2uhP38WPXKYg" id="(1.0,0.375)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2yIgUYE1Ee2uhP38WPXKYg" id="(0.15079365079365079,0.4444444444444444)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_A_ly04E2Ee2uhP38WPXKYg" type="4001" element="_A_ly0IE2Ee2uhP38WPXKYg" source="_yIVquIE1Ee2uhP38WPXKYg" target="_-nwYyIE1Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_A_ly1oE2Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_A_ly14E2Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_A_ly1IE2Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_A_ly1YE2Ee2uhP38WPXKYg" points="[-64, 36, -1, -109]$[-64, 75, -1, -70]$[-50, 75, 13, -70]$[-50, 115, 13, -30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_A_mZ4IE2Ee2uhP38WPXKYg" id="(1.0,0.42857142857142855)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_G8ICs4E2Ee2uhP38WPXKYg" type="4001" element="_G8ICsIE2Ee2uhP38WPXKYg" source="_-nwYyIE1Ee2uhP38WPXKYg" target="_DZAhRIE2Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_G8ICtoE2Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_G8ICt4E2Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_G8ICtIE2Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_G8ICtYE2Ee2uhP38WPXKYg" points="[0, 1, -127, -3]$[109, 1, -18, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_G8IpwIE2Ee2uhP38WPXKYg" id="(1.0,0.4166666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_NX3XEIE2Ee2uhP38WPXKYg" type="4001" element="_NX2I8IE2Ee2uhP38WPXKYg" source="_DZAhRIE2Ee2uhP38WPXKYg" target="_KkuhGYE2Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_NX3XE4E2Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_NX3XFIE2Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_NX3XEYE2Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_NX3XEoE2Ee2uhP38WPXKYg" points="[-4, -10, -1, 139]$[-4, -119, -1, 30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_NX4lMIE2Ee2uhP38WPXKYg" id="(1.0,0.627906976744186)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_QunQcoE2Ee2uhP38WPXKYg" type="4001" element="_QumpYIE2Ee2uhP38WPXKYg" source="_KkuhGYE2Ee2uhP38WPXKYg" target="_PThLc4E2Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_QunQdYE2Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_QunQdoE2Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QunQc4E2Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_QunQdIE2Ee2uhP38WPXKYg" points="[-14, -25, 53, 96]$[-64, -136, 3, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_QuoekIE2Ee2uhP38WPXKYg" id="(1.0,0.4166666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_WcSk8IE2Ee2uhP38WPXKYg" type="4001" element="_WcR94IE2Ee2uhP38WPXKYg" source="_DZAhRIE2Ee2uhP38WPXKYg" target="_Sbx84IE2Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_WcSk84E2Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_WcSk9IE2Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_WcSk8YE2Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_WcSk8oE2Ee2uhP38WPXKYg" points="[-10, 0, -214, 9]$[206, -29, 2, -20]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_WcTMAIE2Ee2uhP38WPXKYg" id="(1.0,0.6976744186046512)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Wx3MUIE2Ee2uhP38WPXKYg" type="4001" element="_Wx1-MIE2Ee2uhP38WPXKYg" source="_Sbx84IE2Ee2uhP38WPXKYg" target="_SzSd9IE2Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Wx3zYIE2Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Wx3zYYE2Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Wx3MUYE2Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Wx3MUoE2Ee2uhP38WPXKYg" points="[-2, 0, -257, 2]$[252, 16, -3, 18]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Wx5BgIE2Ee2uhP38WPXKYg" id="(1.0,0.5348837209302325)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_XGxFUIE2Ee2uhP38WPXKYg" type="4001" element="_XGweQIE2Ee2uhP38WPXKYg" source="_SzSd9IE2Ee2uhP38WPXKYg" target="_TG0d8IE2Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_XGxFU4E2Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_XGxFVIE2Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_XGxFUYE2Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_XGxFUoE2Ee2uhP38WPXKYg" points="[-4, 1, -198, 4]$[176, 1, -18, 4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_XGxsYIE2Ee2uhP38WPXKYg" id="(1.0,0.5581395348837209)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_biXt84E2Ee2uhP38WPXKYg" type="4001" element="_biXt8IE2Ee2uhP38WPXKYg" source="_DZAhRIE2Ee2uhP38WPXKYg" target="_YL3FKIE2Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_biXt9oE2Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_biXt94E2Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_biXt9IE2Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_biXt9YE2Ee2uhP38WPXKYg" points="[-24, 10, -3, -149]$[-51, 129, -30, -30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_biaKMIE2Ee2uhP38WPXKYg" id="(1.0,0.7209302325581395)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_HJFEI4E3Ee2uhP38WPXKYg" type="4001" element="_HJFEIIE3Ee2uhP38WPXKYg" source="_YL3FKIE2Ee2uhP38WPXKYg" target="_vaZBQ4E2Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_HJFEJoE3Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_HJFEJ4E3Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_HJFEJIE3Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_HJFEJYE3Ee2uhP38WPXKYg" points="[-17, 34, 37, -79]$[-60, 126, -6, 13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_HJGSQIE3Ee2uhP38WPXKYg" id="(1.0,0.43333333333333335)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_HiebkYE3Ee2uhP38WPXKYg" type="4001" element="_Hid0gIE3Ee2uhP38WPXKYg" source="_5xZRWIE2Ee2uhP38WPXKYg" target="_wnH6JIE2Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_HieblIE3Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_HieblYE3Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_HiebkoE3Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Hiebk4E3Ee2uhP38WPXKYg" points="[-18, 30, 50, -86]$[-72, 118, -4, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_HifCoIE3Ee2uhP38WPXKYg" id="(1.0,0.5)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_HifCoYE3Ee2uhP38WPXKYg" id="(0.23333333333333334,0.7333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_H4Rsc4E3Ee2uhP38WPXKYg" type="4001" element="_H4RscIE3Ee2uhP38WPXKYg" source="_9fn2mIE2Ee2uhP38WPXKYg" target="_yI9gUIE2Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_H4STgIE3Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_H4STgYE3Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_H4RsdIE3Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_H4RsdYE3Ee2uhP38WPXKYg" points="[-18, 32, 46, -85]$[-68, 118, -4, 1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_H4S6kIE3Ee2uhP38WPXKYg" id="(1.0,0.4666666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_H4S6kYE3Ee2uhP38WPXKYg" id="(0.16666666666666666,0.7)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IJG9w4E3Ee2uhP38WPXKYg" type="4001" element="_IJG9wIE3Ee2uhP38WPXKYg" source="_CvYgAIE3Ee2uhP38WPXKYg" target="_yztGc4E2Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IJG9xoE3Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IJG9x4E3Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IJG9xIE3Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IJG9xYE3Ee2uhP38WPXKYg" points="[-17, 34, 43, -89]$[-60, 127, 0, 4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IJIL4IE3Ee2uhP38WPXKYg" id="(1.0,0.43333333333333335)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IJIL4YE3Ee2uhP38WPXKYg" id="(0.5,0.8333333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_KxhxgoE3Ee2uhP38WPXKYg" type="4001" element="_KxgjYIE3Ee2uhP38WPXKYg" source="_Sbx84IE2Ee2uhP38WPXKYg" target="_5xZRWIE2Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_KxhxhYE3Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_KxhxhoE3Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Kxhxg4E3Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_KxhxhIE3Ee2uhP38WPXKYg" points="[-23, 12, -2, -153]$[-27, 135, -6, -30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_KxiYkIE3Ee2uhP38WPXKYg" id="(1.0,0.7209302325581395)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_LXOfk4E3Ee2uhP38WPXKYg" type="4001" element="_LXOfkIE3Ee2uhP38WPXKYg" source="_SzSd9IE2Ee2uhP38WPXKYg" target="_9fn2mIE2Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_LXOfloE3Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_LXOfl4E3Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_LXOflIE3Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_LXOflYE3Ee2uhP38WPXKYg" points="[-22, 14, -1, -153]$[-25, 137, -4, -30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_LXPGoIE3Ee2uhP38WPXKYg" id="(1.0,0.6744186046511628)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Lz0U84E3Ee2uhP38WPXKYg" type="4001" element="_Lz0U8IE3Ee2uhP38WPXKYg" source="_TG0d8IE2Ee2uhP38WPXKYg" target="_CvYgAIE3Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Lz0U9oE3Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Lz0U94E3Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Lz0U9IE3Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Lz0U9YE3Ee2uhP38WPXKYg" points="[-22, 15, 3, -180]$[-26, 198, -1, 3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Lz08AIE3Ee2uhP38WPXKYg" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Lz08AYE3Ee2uhP38WPXKYg" id="(0.4666666666666667,0.95)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PTEDA4E3Ee2uhP38WPXKYg" type="4001" element="_PTEDAIE3Ee2uhP38WPXKYg" source="_GTNTcIE0Ee2uhP38WPXKYg" target="_Sbx84IE2Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_PTEDBoE3Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PTEDB4E3Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PTEDBIE3Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PTEDBYE3Ee2uhP38WPXKYg" points="[-23, 9, 11, -400]$[-42, 422, -8, 13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_PTEqEIE3Ee2uhP38WPXKYg" id="(1.0,0.7674418604651163)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8J3vIIE3Ee2uhP38WPXKYg" type="4001" element="_8J3IEIE3Ee2uhP38WPXKYg" source="_SzSd9IE2Ee2uhP38WPXKYg" target="_eoxBuYE3Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8J3vI4E3Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8J3vJIE3Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8J3vIYE3Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8J3vIoE3Ee2uhP38WPXKYg" points="[-5, -11, 6, 114]$[-5, -155, 6, -30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8J4WMIE3Ee2uhP38WPXKYg" id="(1.0,0.627906976744186)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_-poWIIE3Ee2uhP38WPXKYg" type="4001" element="_-pnvEIE3Ee2uhP38WPXKYg" source="_eoxBuYE3Ee2uhP38WPXKYg" target="_fCr9kIE3Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_-poWI4E3Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_-poWJIE3Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_-poWIYE3Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_-poWIoE3Ee2uhP38WPXKYg" points="[-8, -32, 42, 157]$[-46, -154, 4, 35]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_-po9MIE3Ee2uhP38WPXKYg" id="(1.0,0.5333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__DKQcIE3Ee2uhP38WPXKYg" type="4001" element="__DJpYIE3Ee2uhP38WPXKYg" source="_fCr9kIE3Ee2uhP38WPXKYg" target="_gTKuAIE3Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__DKQc4E3Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__DKQdIE3Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__DKQcYE3Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__DKQcoE3Ee2uhP38WPXKYg" points="[-19, -26, 50, 79]$[-71, -91, -2, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="__DK3gIE3Ee2uhP38WPXKYg" id="(1.0,0.37142857142857144)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__rATk4E3Ee2uhP38WPXKYg" type="4001" element="__rATkIE3Ee2uhP38WPXKYg" source="_TG0d8IE2Ee2uhP38WPXKYg" target="_fkitcIE3Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__rATloE3Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__rATl4E3Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__rATlIE3Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__rATlYE3Ee2uhP38WPXKYg" points="[-2, -10, 19, 117]$[-18, -97, 3, 30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="__rA6oIE3Ee2uhP38WPXKYg" id="(1.0,0.6744186046511628)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="____FE4E3Ee2uhP38WPXKYg" type="4001" element="____FEIE3Ee2uhP38WPXKYg" source="_fkitcIE3Ee2uhP38WPXKYg" target="_g_Pw5IE3Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="____FFoE3Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="____FF4E3Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="____FFIE3Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="____FFYE3Ee2uhP38WPXKYg" points="[-11, -34, 49, 142]$[-55, -191, 5, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AAATMIE4Ee2uhP38WPXKYg" id="(1.0,0.5666666666666667)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
