<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_Jhq2sIE4Ee2uhP38WPXKYg" name="Yataklı Servis Hizmetleri Süreci" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_Jhq2sYE4Ee2uhP38WPXKYg" name="Pool">
      <elements xmi:type="process:Lane" xmi:id="_Jhq2soE4Ee2uhP38WPXKYg" name="Employee lane" actor="_Jhq2y4E4Ee2uhP38WPXKYg">
        <elements xmi:type="process:StartEvent" xmi:id="_Jhq2s4E4Ee2uhP38WPXKYg" name="Start1" outgoing="_Jhq2yIE4Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Jhq2tIE4Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Jhq2tYE4Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Jhq2toE4Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_Jhq2t4E4Ee2uhP38WPXKYg" name="Yatış işlemleri yapılmış hastanın ilgili servise müraacatı" outgoing="_H4H3QIE-Ee2uhP38WPXKYg" incoming="_Jhq2yIE4Ee2uhP38WPXKYg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Jhq2uIE4Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Jhq2uYE4Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Jhq2uoE4Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Jhq2u4E4Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Jhq2vIE4Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Jhq2vYE4Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Jhq2voE4Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Jhq2v4E4Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Jhq2wIE4Ee2uhP38WPXKYg">
            <targetForm xmi:type="expression:Expression" xmi:id="_Jhq2wYE4Ee2uhP38WPXKYg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Jhq2woE4Ee2uhP38WPXKYg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Jhq2w4E4Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_bfeDkIE5Ee2uhP38WPXKYg" name="Evrakların servis sekreteri tarafından kontrolü" outgoing="_IhQT0IE-Ee2uhP38WPXKYg" incoming="_H4H3QIE-Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_bfeDkoE5Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_bfeDkYE5Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_bfeDk4E5Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_bfeDlIE5Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_bfeDlYE5Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_bfeDloE5Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_bfeDmIE5Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_bfeDl4E5Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:InclusiveGateway" xmi:id="_kbCQYIE5Ee2uhP38WPXKYg" name="Hastanın sosyal güvencesi var mı ?" outgoing="_Jg_5kIE-Ee2uhP38WPXKYg _KW7cAIE-Ee2uhP38WPXKYg" incoming="_IhQT0IE-Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kbCQYoE5Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kbCQYYE5Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kbCQY4E5Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_nxenwIE5Ee2uhP38WPXKYg" name="İşlemlerim ücretli olarak yapılması" outgoing="_MvnxsIE-Ee2uhP38WPXKYg" incoming="_KW7cAIE-Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_nxenwoE5Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_nxenwYE5Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_nxenw4E5Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_nxenxIE5Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_nxenxYE5Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_nxenxoE5Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_nxenyIE5Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_nxenx4E5Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:InclusiveGateway" xmi:id="_qT6IQIE5Ee2uhP38WPXKYg" name="Eksik evrak var mı" outgoing="_iM9dAIE-Ee2uhP38WPXKYg" incoming="_Jg_5kIE-Ee2uhP38WPXKYg _MvnxsIE-Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qT6IQoE5Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qT6IQYE5Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qT6IQ4E5Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_s5LhYIE5Ee2uhP38WPXKYg" name="Evrakların tamamlanması">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_s5LhYoE5Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_s5LhYYE5Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_s5LhY4E5Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_s5LhZIE5Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_s5LhZYE5Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_s5LhZoE5Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_s5LhaIE5Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_s5LhZ4E5Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ReceiveTask" xmi:id="_yLE40IE5Ee2uhP38WPXKYg" name="Hasta kaydının yapılması" outgoing="_igdn0IE-Ee2uhP38WPXKYg" incoming="_iM9dAIE-Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_yLFf4YE5Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_yLFf4IE5Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_yLFf4oE5Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_yLFf44E5Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_yLFf5IE5Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_yLFf5YE5Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_yLFf54E5Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_yLFf5oE5Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_11PdcIE5Ee2uhP38WPXKYg" name="Tetkiklerin ilgili merkez tarafından yapılması" outgoing="_yTe0oIE-Ee2uhP38WPXKYg" incoming="_kLipkIE-Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_11PdcoE5Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_11PdcYE5Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_11Pdc4E5Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_11PddIE5Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_11PddYE5Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_11QEgIE5Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_11QEgoE5Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_11QEgYE5Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_Z5z34IE6Ee2uhP38WPXKYg" name="Hastane üst yönetiminin onayının alınması" outgoing="_kLipkIE-Ee2uhP38WPXKYg" incoming="_j2-u0IE-Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Z5z34oE6Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Z5z34YE6Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Z5z344E6Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Z5z35IE6Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Z5z35YE6Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Z5z35oE6Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Z5z36IE6Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Z5z354E6Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_eRu6YIE6Ee2uhP38WPXKYg" name="İlgili tetkik merkezine hastanın sevki" outgoing="_j2-u0IE-Ee2uhP38WPXKYg" incoming="_pkymMIE-Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_eRu6YoE6Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_eRu6YYE6Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_eRu6Y4E6Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_eRu6ZIE6Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_eRu6ZYE6Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_eRu6ZoE6Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_eRu6aIE6Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_eRu6Z4E6Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_v1qEIIE6Ee2uhP38WPXKYg" name="Hastanın servise kabulü" outgoing="_nEFkAIE-Ee2uhP38WPXKYg" incoming="_igdn0IE-Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_v1qrMYE6Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_v1qrMIE6Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_v1qrMoE6Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_v1qrM4E6Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_v1qrNIE6Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_v1qrNYE6Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_v1qrN4E6Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_v1qrNoE6Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_z3I8kIE6Ee2uhP38WPXKYg" name="Hastanın muaynesinin servis doktoru tarafından yapılmasu" outgoing="_nvDzoIE-Ee2uhP38WPXKYg" incoming="_nEFkAIE-Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_z3I8koE6Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_z3I8kYE6Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_z3I8k4E6Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_z3I8lIE6Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_z3I8lYE6Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_z3JjoIE6Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_z3JjooE6Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_z3JjoYE6Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:InclusiveGateway" xmi:id="_4M2YkIE6Ee2uhP38WPXKYg" name="Tetkik gerekiyor mu ?" outgoing="_5hzcgIE-Ee2uhP38WPXKYg _70ROYIE-Ee2uhP38WPXKYg" incoming="_nvDzoIE-Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_4M2YkoE6Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_4M2YkYE6Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_4M2Yk4E6Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:InclusiveGateway" xmi:id="_6SvHAIE6Ee2uhP38WPXKYg" name="Tetkikler hastane imkanları ile yapıabilir mi" outgoing="_pkymMIE-Ee2uhP38WPXKYg _qZ5pQIE-Ee2uhP38WPXKYg" incoming="_5hzcgIE-Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_6SvuEYE6Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_6SvuEIE6Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_6SvuEoE6Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="__tgtoIE6Ee2uhP38WPXKYg" name="Tetkiklerin yapılması" outgoing="_sBR2wIE-Ee2uhP38WPXKYg" incoming="_qZ5pQIE-Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="__tgtooE6Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="__tgtoYE6Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="__tgto4E6Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="__tgtpIE6Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="__tgtpYE6Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="__tgtpoE6Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="__tgtqIE6Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="__tgtp4E6Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_C0iwAIE7Ee2uhP38WPXKYg" name="Hastayı tedavi yönetminin belirlenmesi" outgoing="_sTOiYIE-Ee2uhP38WPXKYg" incoming="_sBR2wIE-Ee2uhP38WPXKYg _yTe0oIE-Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_C0iwAoE7Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_C0iwAYE7Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_C0iwA4E7Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_C0iwBIE7Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_C0iwBYE7Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_C0iwBoE7Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_C0iwCIE7Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_C0iwB4E7Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_FvPmkIE7Ee2uhP38WPXKYg" name="Tedavinin başlatılması" incoming="_sTOiYIE-Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_FvPmkoE7Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_FvPmkYE7Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_FvPmk4E7Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_FvPmlIE7Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_FvPmlYE7Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_FvPmloE7Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_FvPmmIE7Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_FvPml4E7Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:InclusiveGateway" xmi:id="_KF0lQIE7Ee2uhP38WPXKYg" name="Sonuç" outgoing="__LeawIE-Ee2uhP38WPXKYg _EtBXwIE_Ee2uhP38WPXKYg" incoming="_70ROYIE-Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_KF0lQoE7Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_KF0lQYE7Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_KF0lQ4E7Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:InclusiveGateway" xmi:id="_L0KWYIE7Ee2uhP38WPXKYg" name="Sonuç" outgoing="_FTeTwIE_Ee2uhP38WPXKYg _IQNKoIE_Ee2uhP38WPXKYg _MQ4KwIE_Ee2uhP38WPXKYg" incoming="_EtBXwIE_Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_L0KWYoE7Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_L0KWYYE7Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_L0KWY4E7Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_VtNpsIE8Ee2uhP38WPXKYg" name="Sevk işlemlerinin yapılması" outgoing="_KSxfUIE_Ee2uhP38WPXKYg" incoming="_IQNKoIE_Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_VtOQwYE8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_VtOQwIE8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_VtOQwoE8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_VtOQw4E8Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_VtOQxIE8Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_VtOQxYE8Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_VtOQx4E8Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_VtOQxoE8Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_Ypi38IE8Ee2uhP38WPXKYg" name="Hastane üst yönetiminin onayının alınması" outgoing="_KlxT0IE_Ee2uhP38WPXKYg" incoming="_KSxfUIE_Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Ypi38oE8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Ypi38YE8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Ypi384E8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Ypi39IE8Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Ypi39YE8Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Ypi39oE8Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Ypi3-IE8Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Ypi394E8Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ReceiveTask" xmi:id="_bV2tMIE8Ee2uhP38WPXKYg" name="Reçetenin  doktor  tarafından yazılması" outgoing="_BRwKwIE_Ee2uhP38WPXKYg" incoming="__LeawIE-Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_bV2tMoE8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_bV2tMYE8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_bV2tM4E8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_bV2tNIE8Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_bV2tNYE8Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_bV2tNoE8Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_bV2tOIE8Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_bV2tN4E8Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_l1NA8IE8Ee2uhP38WPXKYg" name="Son" incoming="_BRwKwIE_Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_l1NA8oE8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_l1NA8YE8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_l1NA84E8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_mjseoIE8Ee2uhP38WPXKYg" name="Son" incoming="_KlxT0IE_Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_mjseooE8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_mjseoYE8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_mjseo4E8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_sn41sIE8Ee2uhP38WPXKYg" name="Defin işlemlerinin başlatılması" outgoing="_HCOUkIE_Ee2uhP38WPXKYg" incoming="_FTeTwIE_Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_sn5cwYE8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_sn5cwIE8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_sn5cwoE8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_sn5cw4E8Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_sn5cxIE8Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_sn5cxYE8Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_sn5cx4E8Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_sn5cxoE8Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_vheR8IE8Ee2uhP38WPXKYg" name="Son" incoming="_HCOUkIE_Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_vheR8oE8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_vheR8YE8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_vheR84E8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ReceiveTask" xmi:id="_xOqzkIE8Ee2uhP38WPXKYg" name="Ameliyat kayıtlarınınn yapılması" outgoing="_NY14YIE_Ee2uhP38WPXKYg" incoming="_MQ4KwIE_Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xOraoYE8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xOraoIE8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xOraooE8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_xOrao4E8Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_xOrapIE8Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_xOrapYE8Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_xOrap4E8Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_xOrapoE8Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_0IPBsIE8Ee2uhP38WPXKYg" name="Ameliyatın yapılması" outgoing="_NnmtIIE_Ee2uhP38WPXKYg" incoming="_NY14YIE_Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0IPBsoE8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0IPBsYE8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0IPBs4E8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0IPBtIE8Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0IPBtYE8Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0IPBtoE8Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0IPBuIE8Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0IPBt4E8Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_2is5AIE8Ee2uhP38WPXKYg" name="Hastanın servise geri alınması" outgoing="_OKszIIE_Ee2uhP38WPXKYg" incoming="_NnmtIIE_Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_2is5AoE8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_2is5AYE8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_2is5A4E8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_2is5BIE8Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_2is5BYE8Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_2is5BoE8Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_2is5CIE8Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_2is5B4E8Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_5lJ9YIE8Ee2uhP38WPXKYg" name="Taburcu işlemlerinin yapılması" outgoing="_Oqj-8IE_Ee2uhP38WPXKYg" incoming="_OKszIIE_Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5lJ9YoE8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5lJ9YYE8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5lJ9Y4E8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_5lJ9ZIE8Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_5lJ9ZYE8Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_5lJ9ZoE8Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_5lJ9aIE8Ee2uhP38WPXKYg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_5lJ9Z4E8Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_7F6lgIE8Ee2uhP38WPXKYg" name="Son" incoming="_Oqj-8IE_Ee2uhP38WPXKYg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_7F6lgoE8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_7F6lgYE8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_7F6lg4E8Ee2uhP38WPXKYg" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_Jhq2xIE4Ee2uhP38WPXKYg">
        <targetForm xmi:type="expression:Expression" xmi:id="_Jhq2xYE4Ee2uhP38WPXKYg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_Jhq2xoE4Ee2uhP38WPXKYg">
        <targetForm xmi:type="expression:Expression" xmi:id="_Jhq2x4E4Ee2uhP38WPXKYg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Jhq2yIE4Ee2uhP38WPXKYg" target="_Jhq2t4E4Ee2uhP38WPXKYg" source="_Jhq2s4E4Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Jhq2yYE4Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_Jhq2yoE4Ee2uhP38WPXKYg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_H4H3QIE-Ee2uhP38WPXKYg" target="_bfeDkIE5Ee2uhP38WPXKYg" source="_Jhq2t4E4Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_H4H3QYE-Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_H4H3QoE-Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IhQT0IE-Ee2uhP38WPXKYg" target="_kbCQYIE5Ee2uhP38WPXKYg" source="_bfeDkIE5Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IhQ64IE-Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_IhQ64YE-Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Jg_5kIE-Ee2uhP38WPXKYg" name="Evet" target="_qT6IQIE5Ee2uhP38WPXKYg" source="_kbCQYIE5Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Jg_5kYE-Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_Jg_5koE-Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_KW7cAIE-Ee2uhP38WPXKYg" name="Hayır" target="_nxenwIE5Ee2uhP38WPXKYg" source="_kbCQYIE5Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_KW7cAYE-Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_KW7cAoE-Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_MvnxsIE-Ee2uhP38WPXKYg" target="_qT6IQIE5Ee2uhP38WPXKYg" source="_nxenwIE5Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_MvnxsYE-Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_MvnxsoE-Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_iM9dAIE-Ee2uhP38WPXKYg" target="_yLE40IE5Ee2uhP38WPXKYg" source="_qT6IQIE5Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_iM9dAYE-Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_iM9dAoE-Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_igdn0IE-Ee2uhP38WPXKYg" target="_v1qEIIE6Ee2uhP38WPXKYg" source="_yLE40IE5Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_igeO4IE-Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_igeO4YE-Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_j2-u0IE-Ee2uhP38WPXKYg" target="_Z5z34IE6Ee2uhP38WPXKYg" source="_eRu6YIE6Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_j2-u0YE-Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_j2-u0oE-Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kLipkIE-Ee2uhP38WPXKYg" target="_11PdcIE5Ee2uhP38WPXKYg" source="_Z5z34IE6Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kLipkYE-Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_kLipkoE-Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_nEFkAIE-Ee2uhP38WPXKYg" target="_z3I8kIE6Ee2uhP38WPXKYg" source="_v1qEIIE6Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_nEFkAYE-Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_nEFkAoE-Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_nvDzoIE-Ee2uhP38WPXKYg" target="_4M2YkIE6Ee2uhP38WPXKYg" source="_z3I8kIE6Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_nvDzoYE-Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_nvDzooE-Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_pkymMIE-Ee2uhP38WPXKYg" name="Hayır" target="_eRu6YIE6Ee2uhP38WPXKYg" source="_6SvHAIE6Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_pkymMYE-Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_pkymMoE-Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qZ5pQIE-Ee2uhP38WPXKYg" name="Evet" target="__tgtoIE6Ee2uhP38WPXKYg" source="_6SvHAIE6Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qZ5pQYE-Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_qZ5pQoE-Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_sBR2wIE-Ee2uhP38WPXKYg" target="_C0iwAIE7Ee2uhP38WPXKYg" source="__tgtoIE6Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_sBR2wYE-Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_sBR2woE-Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_sTOiYIE-Ee2uhP38WPXKYg" target="_FvPmkIE7Ee2uhP38WPXKYg" source="_C0iwAIE7Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_sTOiYYE-Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_sTOiYoE-Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_yTe0oIE-Ee2uhP38WPXKYg" target="_C0iwAIE7Ee2uhP38WPXKYg" source="_11PdcIE5Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_yTe0oYE-Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_yTe0ooE-Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_5hzcgIE-Ee2uhP38WPXKYg" name="Evet" target="_6SvHAIE6Ee2uhP38WPXKYg" source="_4M2YkIE6Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_5hzcgYE-Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_5hzcgoE-Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_70ROYIE-Ee2uhP38WPXKYg" name="Hayır" target="_KF0lQIE7Ee2uhP38WPXKYg" source="_4M2YkIE6Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_70ROYYE-Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_70ROYoE-Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__LeawIE-Ee2uhP38WPXKYg" name="Taburcu" target="_bV2tMIE8Ee2uhP38WPXKYg" source="_KF0lQIE7Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__LeawYE-Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="__LeawoE-Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BRwKwIE_Ee2uhP38WPXKYg" target="_l1NA8IE8Ee2uhP38WPXKYg" source="_bV2tMIE8Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BRwKwYE_Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_BRwKwoE_Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_EtBXwIE_Ee2uhP38WPXKYg" target="_L0KWYIE7Ee2uhP38WPXKYg" source="_KF0lQIE7Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_EtBXwYE_Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_EtBXwoE_Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_FTeTwIE_Ee2uhP38WPXKYg" name="Ölüm" target="_sn41sIE8Ee2uhP38WPXKYg" source="_L0KWYIE7Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_FTeTwYE_Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_FTeTwoE_Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_HCOUkIE_Ee2uhP38WPXKYg" target="_vheR8IE8Ee2uhP38WPXKYg" source="_sn41sIE8Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_HCOUkYE_Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_HCOUkoE_Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IQNKoIE_Ee2uhP38WPXKYg" name="Sevk" target="_VtNpsIE8Ee2uhP38WPXKYg" source="_L0KWYIE7Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IQNKoYE_Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_IQNKooE_Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_KSxfUIE_Ee2uhP38WPXKYg" target="_Ypi38IE8Ee2uhP38WPXKYg" source="_VtNpsIE8Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_KSxfUYE_Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_KSxfUoE_Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_KlxT0IE_Ee2uhP38WPXKYg" target="_mjseoIE8Ee2uhP38WPXKYg" source="_Ypi38IE8Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Klx64IE_Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_Klx64YE_Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_MQ4KwIE_Ee2uhP38WPXKYg" name="Ameliyat" target="_xOqzkIE8Ee2uhP38WPXKYg" source="_L0KWYIE7Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_MQ4KwYE_Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_MQ4KwoE_Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_NY14YIE_Ee2uhP38WPXKYg" target="_0IPBsIE8Ee2uhP38WPXKYg" source="_xOqzkIE8Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_NY14YYE_Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_NY14YoE_Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_NnmtIIE_Ee2uhP38WPXKYg" target="_2is5AIE8Ee2uhP38WPXKYg" source="_0IPBsIE8Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_NnmtIYE_Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_NnmtIoE_Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_OKszIIE_Ee2uhP38WPXKYg" name="Taburcu" target="_5lJ9YIE8Ee2uhP38WPXKYg" source="_2is5AIE8Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_OKszIYE_Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_OKszIoE_Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Oqj-8IE_Ee2uhP38WPXKYg" target="_7F6lgIE8Ee2uhP38WPXKYg" source="_5lJ9YIE8Ee2uhP38WPXKYg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Oqj-8YE_Ee2uhP38WPXKYg"/>
        <condition xmi:type="expression:Expression" xmi:id="_OqkmAIE_Ee2uhP38WPXKYg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_Jhq2y4E4Ee2uhP38WPXKYg" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_Jhq2zIE4Ee2uhP38WPXKYg"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Jhq2zYE4Ee2uhP38WPXKYg">
        <name xmi:type="expression:Expression" xmi:id="_Jhq2zoE4Ee2uhP38WPXKYg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Jhq2z4E4Ee2uhP38WPXKYg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Jhq20IE4Ee2uhP38WPXKYg">
        <name xmi:type="expression:Expression" xmi:id="_Jhq20YE4Ee2uhP38WPXKYg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Jhq20oE4Ee2uhP38WPXKYg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Jhq204E4Ee2uhP38WPXKYg">
        <name xmi:type="expression:Expression" xmi:id="_Jhq21IE4Ee2uhP38WPXKYg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Jhq21YE4Ee2uhP38WPXKYg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Jhq21oE4Ee2uhP38WPXKYg">
        <name xmi:type="expression:Expression" xmi:id="_Jhq214E4Ee2uhP38WPXKYg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Jhq22IE4Ee2uhP38WPXKYg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Jhq22YE4Ee2uhP38WPXKYg">
        <name xmi:type="expression:Expression" xmi:id="_Jhq22oE4Ee2uhP38WPXKYg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Jhq224E4Ee2uhP38WPXKYg" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_Jhq23IE4Ee2uhP38WPXKYg" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_Jhq23YE4Ee2uhP38WPXKYg" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_Jhq23oE4Ee2uhP38WPXKYg" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_Jhq234E4Ee2uhP38WPXKYg" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_Jhq24IE4Ee2uhP38WPXKYg" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_Jhq24YE4Ee2uhP38WPXKYg" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_Jhq24oE4Ee2uhP38WPXKYg" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_Jhq244E4Ee2uhP38WPXKYg" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_Jhq25IE4Ee2uhP38WPXKYg" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_Jhq25YE4Ee2uhP38WPXKYg" type="Process" element="_Jhq2sIE4Ee2uhP38WPXKYg" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_Jhq25oE4Ee2uhP38WPXKYg" type="2007" element="_Jhq2sYE4Ee2uhP38WPXKYg">
      <children xmi:type="notation:DecorationNode" xmi:id="_Jhq254E4Ee2uhP38WPXKYg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_Jhq26IE4Ee2uhP38WPXKYg" type="7001">
        <children xmi:type="notation:Node" xmi:id="_Jhq26YE4Ee2uhP38WPXKYg" type="3007" element="_Jhq2soE4Ee2uhP38WPXKYg">
          <children xmi:type="notation:DecorationNode" xmi:id="_Jhq26oE4Ee2uhP38WPXKYg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_Jhq264E4Ee2uhP38WPXKYg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_Jhq27IE4Ee2uhP38WPXKYg" type="3005" element="_Jhq2t4E4Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Jhq27YE4Ee2uhP38WPXKYg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Jhq27oE4Ee2uhP38WPXKYg" x="158" y="66" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Jhq274E4Ee2uhP38WPXKYg" type="3002" element="_Jhq2s4E4Ee2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Jhq28IE4Ee2uhP38WPXKYg" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Jhq28YE4Ee2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Jhq28oE4Ee2uhP38WPXKYg" x="60" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_bffRsIE5Ee2uhP38WPXKYg" type="3006" element="_bfeDkIE5Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_bffRsoE5Ee2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bffRsYE5Ee2uhP38WPXKYg" x="422" y="68" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kbCQZIE5Ee2uhP38WPXKYg" type="3051" element="_kbCQYIE5Ee2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_kbCQZoE5Ee2uhP38WPXKYg" type="5075">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_kbCQZ4E5Ee2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kbCQZYE5Ee2uhP38WPXKYg" x="550" y="203"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_nxfO0IE5Ee2uhP38WPXKYg" type="3006" element="_nxenwIE5Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_nxfO0oE5Ee2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_nxfO0YE5Ee2uhP38WPXKYg" x="178" y="186" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_qT6vUIE5Ee2uhP38WPXKYg" type="3051" element="_qT6IQIE5Ee2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_qT6vUoE5Ee2uhP38WPXKYg" type="5075">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_qT6vU4E5Ee2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qT6vUYE5Ee2uhP38WPXKYg" x="520" y="384"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_s5MIcIE5Ee2uhP38WPXKYg" type="3006" element="_s5LhYIE5Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_s5MIcoE5Ee2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_s5MIcYE5Ee2uhP38WPXKYg" x="690" y="400" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_yLFf6IE5Ee2uhP38WPXKYg" type="3026" element="_yLE40IE5Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_yLFf6oE5Ee2uhP38WPXKYg" type="5012"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yLFf6YE5Ee2uhP38WPXKYg" x="470" y="522" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_11QEg4E5Ee2uhP38WPXKYg" type="3006" element="_11PdcIE5Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_11QEhYE5Ee2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_11QEhIE5Ee2uhP38WPXKYg" x="148" y="378" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Z5z36YE6Ee2uhP38WPXKYg" type="3006" element="_Z5z34IE6Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Z5z364E6Ee2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Z5z36oE6Ee2uhP38WPXKYg" x="158" y="663" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_eRvhcIE6Ee2uhP38WPXKYg" type="3006" element="_eRu6YIE6Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_eRwIgIE6Ee2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eRvhcYE6Ee2uhP38WPXKYg" x="158" y="845" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_v1qrOIE6Ee2uhP38WPXKYg" type="3006" element="_v1qEIIE6Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_v1qrOoE6Ee2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_v1qrOYE6Ee2uhP38WPXKYg" x="482" y="642" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_z3Jjo4E6Ee2uhP38WPXKYg" type="3006" element="_z3I8kIE6Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_z3JjpYE6Ee2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_z3JjpIE6Ee2uhP38WPXKYg" x="472" y="810" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_4M2_oIE6Ee2uhP38WPXKYg" type="3051" element="_4M2YkIE6Ee2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_4M2_ooE6Ee2uhP38WPXKYg" type="5075">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_4M2_o4E6Ee2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4M2_oYE6Ee2uhP38WPXKYg" x="508" y="1012"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_6SvuE4E6Ee2uhP38WPXKYg" type="3051" element="_6SvHAIE6Ee2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_6SvuFYE6Ee2uhP38WPXKYg" type="5075">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_6SvuFoE6Ee2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6SvuFIE6Ee2uhP38WPXKYg" x="206" y="1012"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="__thUsIE6Ee2uhP38WPXKYg" type="3006" element="__tgtoIE6Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="__thUsoE6Ee2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__thUsYE6Ee2uhP38WPXKYg" x="134" y="1170" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_C0iwCYE7Ee2uhP38WPXKYg" type="3006" element="_C0iwAIE7Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_C0iwC4E7Ee2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_C0iwCoE7Ee2uhP38WPXKYg" x="110" y="1309" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_FvQ0sIE7Ee2uhP38WPXKYg" type="3006" element="_FvPmkIE7Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_FvQ0soE7Ee2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_FvQ0sYE7Ee2uhP38WPXKYg" x="134" y="1434" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_KF1MUIE7Ee2uhP38WPXKYg" type="3051" element="_KF0lQIE7Ee2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_KF1MUoE7Ee2uhP38WPXKYg" type="5075">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_KF1MU4E7Ee2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_KF1MUYE7Ee2uhP38WPXKYg" x="508" y="1434"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_L0K9cIE7Ee2uhP38WPXKYg" type="3051" element="_L0KWYIE7Ee2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_L0K9coE7Ee2uhP38WPXKYg" type="5075">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_L0K9c4E7Ee2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_L0K9cYE7Ee2uhP38WPXKYg" x="828" y="1458"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_VtO30IE8Ee2uhP38WPXKYg" type="3006" element="_VtNpsIE8Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_VtO30oE8Ee2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VtO30YE8Ee2uhP38WPXKYg" x="800" y="1602" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ypi3-YE8Ee2uhP38WPXKYg" type="3006" element="_Ypi38IE8Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ypi3-4E8Ee2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ypi3-oE8Ee2uhP38WPXKYg" x="809" y="1746" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_bV3UQIE8Ee2uhP38WPXKYg" type="3026" element="_bV2tMIE8Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_bV3UQoE8Ee2uhP38WPXKYg" type="5012"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bV3UQYE8Ee2uhP38WPXKYg" x="442" y="1637" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_l1NoAIE8Ee2uhP38WPXKYg" type="3003" element="_l1NA8IE8Ee2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_l1NoAoE8Ee2uhP38WPXKYg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_l1NoA4E8Ee2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_l1NoAYE8Ee2uhP38WPXKYg" x="471" y="1842"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_mjsepIE8Ee2uhP38WPXKYg" type="3003" element="_mjseoIE8Ee2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_mjtFsIE8Ee2uhP38WPXKYg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_mjtFsYE8Ee2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_mjsepYE8Ee2uhP38WPXKYg" x="864" y="1872"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_sn5cyIE8Ee2uhP38WPXKYg" type="3006" element="_sn41sIE8Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_sn6D0IE8Ee2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sn5cyYE8Ee2uhP38WPXKYg" x="1046" y="1458" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_vhe5AIE8Ee2uhP38WPXKYg" type="3003" element="_vheR8IE8Ee2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_vhe5AoE8Ee2uhP38WPXKYg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_vhe5A4E8Ee2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vhe5AYE8Ee2uhP38WPXKYg" x="1115" y="1622"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_xOraqIE8Ee2uhP38WPXKYg" type="3026" element="_xOqzkIE8Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_xOraqoE8Ee2uhP38WPXKYg" type="5012"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xOraqYE8Ee2uhP38WPXKYg" x="839" y="1273" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0IPBuYE8Ee2uhP38WPXKYg" type="3006" element="_0IPBsIE8Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0IPowIE8Ee2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0IPBuoE8Ee2uhP38WPXKYg" x="839" y="1146" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_2itgEIE8Ee2uhP38WPXKYg" type="3006" element="_2is5AIE8Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_2itgEoE8Ee2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2itgEYE8Ee2uhP38WPXKYg" x="830" y="995" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_5lKkcIE8Ee2uhP38WPXKYg" type="3006" element="_5lJ9YIE8Ee2uhP38WPXKYg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_5lKkcoE8Ee2uhP38WPXKYg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5lKkcYE8Ee2uhP38WPXKYg" x="854" y="845" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_7F6lhIE8Ee2uhP38WPXKYg" type="3003" element="_7F6lgIE8Ee2uhP38WPXKYg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_7F6lhoE8Ee2uhP38WPXKYg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_7F6lh4E8Ee2uhP38WPXKYg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_7F6lhYE8Ee2uhP38WPXKYg" x="899" y="714"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_Jhq284E4Ee2uhP38WPXKYg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_Jhq29IE4Ee2uhP38WPXKYg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_Jhq29YE4Ee2uhP38WPXKYg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_Jhq29oE4Ee2uhP38WPXKYg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Jhq294E4Ee2uhP38WPXKYg" x="53" y="10" width="1292" height="2073"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_Jhq2-IE4Ee2uhP38WPXKYg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_Jhq2-YE4Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_Jhq2-oE4Ee2uhP38WPXKYg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_Jhq2-4E4Ee2uhP38WPXKYg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Jhq2_IE4Ee2uhP38WPXKYg" width="1320" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_Jhq2_YE4Ee2uhP38WPXKYg"/>
    <edges xmi:type="notation:Connector" xmi:id="_Jhq2_oE4Ee2uhP38WPXKYg" type="4001" element="_Jhq2yIE4Ee2uhP38WPXKYg" source="_Jhq274E4Ee2uhP38WPXKYg" target="_Jhq27IE4Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Jhq2_4E4Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Jhq3AIE4Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Jhq3AYE4Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Jhq3AoE4Ee2uhP38WPXKYg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_H4IeUIE-Ee2uhP38WPXKYg" type="4001" element="_H4H3QIE-Ee2uhP38WPXKYg" source="_Jhq27IE4Ee2uhP38WPXKYg" target="_bffRsIE5Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_H4IeU4E-Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_H4IeVIE-Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_H4IeUYE-Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_H4IeUoE-Ee2uhP38WPXKYg" points="[0, 5, -146, 0]$[124, 5, -22, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_H4JFYIE-Ee2uhP38WPXKYg" id="(1.0,0.45714285714285713)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_H4JFYYE-Ee2uhP38WPXKYg" id="(0.15714285714285714,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IhQ64oE-Ee2uhP38WPXKYg" type="4001" element="_IhQT0IE-Ee2uhP38WPXKYg" source="_bffRsIE5Ee2uhP38WPXKYg" target="_kbCQZIE5Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IhQ65YE-Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IhQ65oE-Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IhQ644E-Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IhQ65IE-Ee2uhP38WPXKYg" points="[-15, 39, 44, -103]$[-56, 161, 3, 19]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IhRh8IE-Ee2uhP38WPXKYg" id="(1.0,0.44285714285714284)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_JhAgoIE-Ee2uhP38WPXKYg" type="4001" element="_Jg_5kIE-Ee2uhP38WPXKYg" source="_kbCQZIE5Ee2uhP38WPXKYg" target="_qT6vUIE5Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_JhAgo4E-Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_JhAgpIE-Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_JhAgoYE-Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JhAgooE-Ee2uhP38WPXKYg" points="[-7, -5, 2, -141]$[-7, 116, 2, -20]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_JhBHsIE-Ee2uhP38WPXKYg" id="(1.0,0.7674418604651163)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_KW7cA4E-Ee2uhP38WPXKYg" type="4001" element="_KW7cAIE-Ee2uhP38WPXKYg" source="_kbCQZIE5Ee2uhP38WPXKYg" target="_nxfO0IE5Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_KW7cBoE-Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_KW7cB4E-Ee2uhP38WPXKYg" x="-6" y="14"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_KW7cBIE-Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_KW7cBYE-Ee2uhP38WPXKYg" points="[-22, -27, 265, 4]$[-135, -27, 152, 4]$[-135, -13, 152, 18]$[-227, -13, 60, 18]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_KW8DEIE-Ee2uhP38WPXKYg" id="(1.0,0.627906976744186)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_MvoYwIE-Ee2uhP38WPXKYg" type="4001" element="_MvnxsIE-Ee2uhP38WPXKYg" source="_nxfO0IE5Ee2uhP38WPXKYg" target="_qT6vUIE5Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_MvoYw4E-Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_MvoYxIE-Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_MvoYwYE-Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_MvoYwoE-Ee2uhP38WPXKYg" points="[-21, 33, -239, -143]$[-21, 93, -239, -83]$[52, 93, -166, -83]$[52, 166, -166, -10]$[207, 166, -11, -10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Mvo_0IE-Ee2uhP38WPXKYg" id="(1.0,0.45)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_iM9dA4E-Ee2uhP38WPXKYg" type="4001" element="_iM9dAIE-Ee2uhP38WPXKYg" source="_qT6vUIE5Ee2uhP38WPXKYg" target="_yLFf6IE5Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_iM9dBoE-Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_iM9dB4E-Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_iM9dBIE-Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_iM9dBYE-Ee2uhP38WPXKYg" points="[-24, 13, 9, -127]$[-36, 170, -3, 30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_iM-EEIE-Ee2uhP38WPXKYg" id="(1.0,0.6511627906976745)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_igeO4oE-Ee2uhP38WPXKYg" type="4001" element="_igdn0IE-Ee2uhP38WPXKYg" source="_yLFf6IE5Ee2uhP38WPXKYg" target="_v1qrOIE6Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_igeO5YE-Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_igeO5oE-Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_igeO44E-Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_igeO5IE-Ee2uhP38WPXKYg" points="[-9, 32, 39, -90]$[12, 121, 60, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ige18IE-Ee2uhP38WPXKYg" id="(1.0,0.4666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_j2-u04E-Ee2uhP38WPXKYg" type="4001" element="_j2-u0IE-Ee2uhP38WPXKYg" source="_eRvhcIE6Ee2uhP38WPXKYg" target="_Z5z36YE6Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_j2-u1oE-Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_j2-u14E-Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_j2-u1IE-Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_j2-u1YE-Ee2uhP38WPXKYg" points="[-5, -30, 45, 147]$[20, -178, 70, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_j2_88IE-Ee2uhP38WPXKYg" id="(1.0,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kLjQoIE-Ee2uhP38WPXKYg" type="4001" element="_kLipkIE-Ee2uhP38WPXKYg" source="_Z5z36YE6Ee2uhP38WPXKYg" target="_11QEg4E5Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_kLjQo4E-Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kLjQpIE-Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kLjQoYE-Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kLjQooE-Ee2uhP38WPXKYg" points="[-5, -26, 75, 250]$[-10, -276, 70, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_kLj3sIE-Ee2uhP38WPXKYg" id="(1.0,0.37142857142857144)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_nEGLEIE-Ee2uhP38WPXKYg" type="4001" element="_nEFkAIE-Ee2uhP38WPXKYg" source="_v1qrOIE6Ee2uhP38WPXKYg" target="_z3Jjo4E6Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_nEGLE4E-Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_nEGLFIE-Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_nEGLEYE-Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_nEGLEoE-Ee2uhP38WPXKYg" points="[-10, 30, 50, -143]$[-55, 208, 5, 35]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_nEGyIIE-Ee2uhP38WPXKYg" id="(1.0,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_nvEasIE-Ee2uhP38WPXKYg" type="4001" element="_nvDzoIE-Ee2uhP38WPXKYg" source="_z3Jjo4E6Ee2uhP38WPXKYg" target="_4M2_oIE6Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_nvEas4E-Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_nvEatIE-Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_nvEasYE-Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_nvEasoE-Ee2uhP38WPXKYg" points="[-19, 40, 52, -119]$[-75, 176, -4, 17]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_nvFBwIE-Ee2uhP38WPXKYg" id="(1.0,0.42857142857142855)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_pkymM4E-Ee2uhP38WPXKYg" type="4001" element="_pkymMIE-Ee2uhP38WPXKYg" source="_6SvuE4E6Ee2uhP38WPXKYg" target="_eRvhcIE6Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pkymNoE-Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pkymN4E-Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pkymNIE-Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_pkymNYE-Ee2uhP38WPXKYg" points="[-19, -23, -7, 140]$[48, -160, 60, 3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_pkz0UIE-Ee2uhP38WPXKYg" id="(1.0,0.6046511627906976)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qZ5pQ4E-Ee2uhP38WPXKYg" type="4001" element="_qZ5pQIE-Ee2uhP38WPXKYg" source="_6SvuE4E6Ee2uhP38WPXKYg" target="__thUsIE6Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qZ6QUIE-Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qZ6QUYE-Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qZ5pRIE-Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qZ5pRYE-Ee2uhP38WPXKYg" points="[-24, 14, 12, -147]$[-41, 191, -5, 30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qZ63YIE-Ee2uhP38WPXKYg" id="(1.0,0.627906976744186)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_sBSd0IE-Ee2uhP38WPXKYg" type="4001" element="_sBR2wIE-Ee2uhP38WPXKYg" source="__thUsIE6Ee2uhP38WPXKYg" target="_C0iwCYE7Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_sBSd04E-Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_sBSd1IE-Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_sBSd0YE-Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_sBSd0oE-Ee2uhP38WPXKYg" points="[-5, 27, 19, -108]$[-21, 165, 3, 30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_sBTE4IE-Ee2uhP38WPXKYg" id="(1.0,0.55)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_sTPJcIE-Ee2uhP38WPXKYg" type="4001" element="_sTOiYIE-Ee2uhP38WPXKYg" source="_C0iwCYE7Ee2uhP38WPXKYg" target="_FvQ0sIE7Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_sTPJc4E-Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_sTPJdIE-Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_sTPJcYE-Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_sTPJcoE-Ee2uhP38WPXKYg" points="[-20, 28, 76, -96]$[-90, 154, 6, 30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_sTPwgIE-Ee2uhP38WPXKYg" id="(1.0,0.5333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_yTe0o4E-Ee2uhP38WPXKYg" type="4001" element="_yTe0oIE-Ee2uhP38WPXKYg" source="_11QEg4E5Ee2uhP38WPXKYg" target="_C0iwCYE7Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_yTfbsIE-Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_yTfbsYE-Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_yTe0pIE-Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_yTe0pYE-Ee2uhP38WPXKYg" points="[-140, 6, 34, -926]$[-229, 6, -55, -926]$[-229, 932, -55, 0]$[-178, 932, -4, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_yTfbsoE-Ee2uhP38WPXKYg" id="(1.0,0.4142857142857143)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_yTfbs4E-Ee2uhP38WPXKYg" id="(0.03333333333333333,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_5hzcg4E-Ee2uhP38WPXKYg" type="4001" element="_5hzcgIE-Ee2uhP38WPXKYg" source="_4M2_oIE6Ee2uhP38WPXKYg" target="_6SvuE4E6Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_5hzchoE-Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_5hzch4E-Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_5hzchIE-Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_5hzchYE-Ee2uhP38WPXKYg" points="[-26, -8, 216, -6]$[-240, -16, 2, -14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_5h0DkIE-Ee2uhP38WPXKYg" id="(1.0,0.5581395348837209)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_70R1cIE-Ee2uhP38WPXKYg" type="4001" element="_70ROYIE-Ee2uhP38WPXKYg" source="_4M2_oIE6Ee2uhP38WPXKYg" target="_KF1MUIE7Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_70R1c4E-Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_70R1dIE-Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_70R1cYE-Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_70R1coE-Ee2uhP38WPXKYg" points="[-16, 8, 0, -301]$[-20, 320, -4, 11]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_70ScgIE-Ee2uhP38WPXKYg" id="(1.0,0.7441860465116279)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__Leaw4E-Ee2uhP38WPXKYg" type="4001" element="__LeawIE-Ee2uhP38WPXKYg" source="_KF1MUIE7Ee2uhP38WPXKYg" target="_bV3UQIE8Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__LfB0IE-Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__LfB0YE-Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__LeaxIE-Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__LeaxYE-Ee2uhP38WPXKYg" points="[-16, 11, -19, -142]$[-42, 154, -45, 1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="__LfB0oE-Ee2uhP38WPXKYg" id="(1.0,0.6744186046511628)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BRwx0IE_Ee2uhP38WPXKYg" type="4001" element="_BRwKwIE_Ee2uhP38WPXKYg" source="_bV3UQIE8Ee2uhP38WPXKYg" target="_l1NoAIE8Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BRwx04E_Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BRwx1IE_Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BRwx0YE_Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BRwx0oE_Ee2uhP38WPXKYg" points="[-11, 23, 55, -127]$[-66, 150, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BRxY4IE_Ee2uhP38WPXKYg" id="(1.0,0.48333333333333334)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BRxY4YE_Ee2uhP38WPXKYg" id="(0.1,0.8)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_EtBXw4E_Ee2uhP38WPXKYg" type="4001" element="_EtBXwIE_Ee2uhP38WPXKYg" source="_KF1MUIE7Ee2uhP38WPXKYg" target="_L0K9cIE7Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_EtBXxoE_Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_EtBXx4E_Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_EtBXxIE_Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_EtBXxYE_Ee2uhP38WPXKYg" points="[-2, -6, -215, 0]$[212, -7, -1, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_EtB-0IE_Ee2uhP38WPXKYg" id="(1.0,0.7674418604651163)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_EtB-0YE_Ee2uhP38WPXKYg" id="(0.16279069767441862,0.37209302325581395)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_FTe60IE_Ee2uhP38WPXKYg" type="4001" element="_FTeTwIE_Ee2uhP38WPXKYg" source="_L0K9cIE7Ee2uhP38WPXKYg" target="_sn5cyIE8Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_FTe604E_Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_FTe61IE_Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_FTe60YE_Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_FTe60oE_Ee2uhP38WPXKYg" points="[-2, -13, -201, -14]$[175, -13, -24, -14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_FTfh4IE_Ee2uhP38WPXKYg" id="(1.0,0.7674418604651163)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_FTfh4YE_Ee2uhP38WPXKYg" id="(0.2,0.5666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_HCO7oIE_Ee2uhP38WPXKYg" type="4001" element="_HCOUkIE_Ee2uhP38WPXKYg" source="_sn5cyIE8Ee2uhP38WPXKYg" target="_vhe5AIE8Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_HCO7o4E_Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_HCO7pIE_Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_HCO7oYE_Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_HCO7ooE_Ee2uhP38WPXKYg" points="[-7, 23, 26, -99]$[-33, 121, 0, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_HCPisIE_Ee2uhP38WPXKYg" id="(1.0,0.5)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_HCPisYE_Ee2uhP38WPXKYg" id="(0.23333333333333334,0.9666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IQNxsIE_Ee2uhP38WPXKYg" type="4001" element="_IQNKoIE_Ee2uhP38WPXKYg" source="_L0K9cIE7Ee2uhP38WPXKYg" target="_VtO30IE8Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IQNxs4E_Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IQNxtIE_Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IQNxsYE_Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IQNxsoE_Ee2uhP38WPXKYg" points="[0, -5, 8, -114]$[0, 87, 8, -22]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IQOYwIE_Ee2uhP38WPXKYg" id="(1.0,0.6511627906976745)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_KSyGYIE_Ee2uhP38WPXKYg" type="4001" element="_KSxfUIE_Ee2uhP38WPXKYg" source="_VtO30IE8Ee2uhP38WPXKYg" target="_Ypi3-YE8Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_KSyGY4E_Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_KSyGZIE_Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_KSyGYYE_Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_KSyGYoE_Ee2uhP38WPXKYg" points="[-2, 18, 29, -89]$[22, 117, 53, 10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_KSytcIE_Ee2uhP38WPXKYg" id="(1.0,0.6)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Klx64oE_Ee2uhP38WPXKYg" type="4001" element="_KlxT0IE_Ee2uhP38WPXKYg" source="_Ypi3-YE8Ee2uhP38WPXKYg" target="_mjsepIE8Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Klx65YE_Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Klx65oE_Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Klx644E_Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Klx65IE_Ee2uhP38WPXKYg" points="[-14, 28, 47, -92]$[-61, 120, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Klyh8IE_Ee2uhP38WPXKYg" id="(1.0,0.4714285714285714)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Klyh8YE_Ee2uhP38WPXKYg" id="(0.13333333333333333,0.8)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_MQ4Kw4E_Ee2uhP38WPXKYg" type="4001" element="_MQ4KwIE_Ee2uhP38WPXKYg" source="_L0K9cIE7Ee2uhP38WPXKYg" target="_xOraqIE8Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_MQ4x0IE_Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_MQ4x0YE_Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_MQ4KxIE_Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_MQ4KxYE_Ee2uhP38WPXKYg" points="[-13, -19, -34, 119]$[-24, -134, -45, 4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_MQ5Y4IE_Ee2uhP38WPXKYg" id="(1.0,0.6511627906976745)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_NY2fcIE_Ee2uhP38WPXKYg" type="4001" element="_NY14YIE_Ee2uhP38WPXKYg" source="_xOraqIE8Ee2uhP38WPXKYg" target="_0IPBuYE8Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_NY2fc4E_Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_NY2fdIE_Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_NY2fcYE_Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_NY2fcoE_Ee2uhP38WPXKYg" points="[-5, -19, 40, 73]$[0, -90, 45, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_NY3GgIE_Ee2uhP38WPXKYg" id="(1.0,0.43333333333333335)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_NnmtI4E_Ee2uhP38WPXKYg" type="4001" element="_NnmtIIE_Ee2uhP38WPXKYg" source="_0IPBuYE8Ee2uhP38WPXKYg" target="_2itgEIE8Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_NnnUMIE_Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_NnnUMYE_Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_NnmtJIE_Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_NnmtJYE_Ee2uhP38WPXKYg" points="[-10, -24, 41, 91]$[-47, -93, 4, 22]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Nnn7QIE_Ee2uhP38WPXKYg" id="(1.0,0.5333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_OKtaMIE_Ee2uhP38WPXKYg" type="4001" element="_OKszIIE_Ee2uhP38WPXKYg" source="_2itgEIE8Ee2uhP38WPXKYg" target="_5lKkcIE8Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_OKtaM4E_Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_OKtaNIE_Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_OKtaMYE_Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_OKtaMoE_Ee2uhP38WPXKYg" points="[-11, -25, 16, 90]$[-72, -113, -45, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_OKuBQIE_Ee2uhP38WPXKYg" id="(1.0,0.55)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_OqkmAYE_Ee2uhP38WPXKYg" type="4001" element="_Oqj-8IE_Ee2uhP38WPXKYg" source="_5lKkcIE8Ee2uhP38WPXKYg" target="_7F6lhIE8Ee2uhP38WPXKYg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_OqkmBIE_Ee2uhP38WPXKYg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_OqkmBYE_Ee2uhP38WPXKYg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_OqkmAoE_Ee2uhP38WPXKYg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_OqkmA4E_Ee2uhP38WPXKYg" points="[-11, -25, 34, 87]$[-46, -102, -1, 10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_OqlNEIE_Ee2uhP38WPXKYg" id="(1.0,0.5666666666666667)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
